# DYD Thermostat Data 

## Preprocess

1. Generated CSV file from queries in BigQueary

2. Data separated into states

3. Aggregated the data in Pandas by month

4. Combine 4 years

5. Group by Identifier

In [1]:
# Dependencies
import pandas as pd
import os
import numpy as np
from pathlib import Path
from datetime import datetime

---
## January

### 2017 January Day

In [2]:
# Read in month csv for state
jan_2017 = pd.read_csv("../data_large/KY-day/2017-jan-day-KY.csv")

# jan_2017

In [3]:
# Add year and month

jan_2017["Year"] = "2017"
jan_2017["Month"] = "Jan"

In [4]:
# Rename columns to label the aggregates

jan_2017.rename(columns={"Temperature_ctrl":"Temperature_ctrl_ave", 
                         "TemperatureExpectedCool":"TemperatureExpectedCool_ave", 
                         "TemperatureExpectedHeat":"TemperatureExpectedHeat_ave"})

,Identifier,date_time,HvacMode,CalendarEvent,Temperature_ctrl_ave,TemperatureExpectedCool_ave,TemperatureExpectedHeat_ave,ProvinceState,City,Age_of_Home__years_,allowCompWithAux,Has_Electric,Has_a_Heat_Pump,Auxilliary_Heat_Fuel_Type,Year,Month
0,96a4ef74ea4ae0b41c2902ac436f65ef8260bc24,2017-01-07 16:55:00 UTC,heat,auto,605,780,620,KY,Prospect,46,True,False,True,Electric,2017,Jan
1,96a4ef74ea4ae0b41c2902ac436f65ef8260bc24,2017-01-23 15:20:00 UTC,heat,hold,673,730,640,KY,Prospect,46,True,False,True,Electric,2017,Jan
2,96a4ef74ea4ae0b41c2902ac436f65ef8260bc24,2017-01-06 16:20:00 UTC,heat,auto,628,730,640,KY,Prospect,46,True,False,True,Electric,2017,Jan
3,96a4ef74ea4ae0b41c2902ac436f65ef8260bc24,2017-01-11 17:50:00 UTC,heat,auto,633,730,640,KY,Prospect,46,True,False,True,Electric,2017,Jan
4,96a4ef74ea4ae0b41c2902ac436f65ef8260bc24,2017-01-06 19:40:00 UTC,heat,auto,630,730,640,KY,Prospect,46,True,False,True,Electric,2017,Jan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113212,ed058081234a88c2d304bb87c8c6a24895c46ec0,2017-01-15 14:40:00 UTC,auto,auto,689,807,653,KY,Nicholasville,10,True,False,True,Electric,2017,Jan
113213,ed058081234a88c2d304bb87c8c6a24895c46ec0,2017-01-10 18:25:00 UTC,auto,auto,680,730,670,KY,Nicholasville,10,True,False,True,Electric,2017,Jan
113214,ed058081234a88c2d304bb87c8c6a24895c46ec0,2017-01-12 18:20:00 UTC,auto,auto,700,740,690,KY,Nicholasville,10,True,False,True,Electric,2017,Jan
113215,ed058081234a88c2d304bb87c8c6a24895c46ec0,2017-01-10 19:00:00 UTC,auto,auto,673,730,670,KY,Nicholasville,10,True,False,True,Electric,2017,Jan
113216,ed058081234a88c2d304bb87c8c6a24895c46ec0,2017-01-08 17:45:00 UTC,auto,auto,628,820,640,KY,Nicholasville,10,True,False,True,Electric,2017,Jan

In [5]:
jan_2017_ave = jan_2017.groupby(['Identifier', 'Month', 'Year','HvacMode','CalendarEvent', 'City']).mean()

# jan_2017_ave

In [6]:
# Export CSV file

jan_2017_ave.to_csv("data/day/KY/jan/jan_2017_ave.csv", header=True, index=True)

### 2018 January Day

In [7]:
# Read in month csv for state
jan_2018 = pd.read_csv("../data_large/KY-day/2018-jan-day-KY.csv")

# jan_2018

In [8]:
# Add year and month

jan_2018["Year"] = "2018"
jan_2018["Month"] = "Jan"

In [9]:
# Rename columns to label the aggregates

jan_2018.rename(columns={"Temperature_ctrl":"Temperature_ctrl_ave", 
                         "TemperatureExpectedCool":"TemperatureExpectedCool_ave", 
                         "TemperatureExpectedHeat":"TemperatureExpectedHeat_ave"})

,Identifier,date_time,HvacMode,CalendarEvent,Temperature_ctrl_ave,TemperatureExpectedCool_ave,TemperatureExpectedHeat_ave,ProvinceState,City,Age_of_Home__years_,allowCompWithAux,Has_Electric,Has_a_Heat_Pump,Auxilliary_Heat_Fuel_Type,Year,Month
0,cbdb5db5ce0fcdae40f28f81305bfbbfa747dc4c,2018-01-27 15:40:00 UTC,auto,hold,675,760,680,KY,Crestview Hills,38,True,False,True,Electric,2018,Jan
1,d117ee90b026d4dc02dbe36b7e9d1d250274bb5d,2018-01-03 10:20:00 UTC,heat,auto,677,680,680,KY,Mt. Washington,47,True,False,True,Electric,2018,Jan
2,d117ee90b026d4dc02dbe36b7e9d1d250274bb5d,2018-01-21 14:50:00 UTC,heat,auto,685,650,600,KY,Mt. Washington,47,True,False,True,Electric,2018,Jan
3,56f54fb3fa14bf1c16c79b63de32965c79394dc5,2018-01-06 11:10:00 UTC,auto,auto,691,745,695,KY,Goshen,36,False,False,True,Electric,2018,Jan
4,cbdb5db5ce0fcdae40f28f81305bfbbfa747dc4c,2018-01-25 17:25:00 UTC,auto,hold,680,760,680,KY,Crestview Hills,38,True,False,True,Electric,2018,Jan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300282,1284a01c8a2c0320c4d7a69983a5e2e33658f3ce,2018-01-31 12:30:00 UTC,heat,hold,596,650,600,KY,Georgetown,120,True,False,True,Electric,2018,Jan
300283,1284a01c8a2c0320c4d7a69983a5e2e33658f3ce,2018-01-02 11:20:00 UTC,heat,hold,644,650,640,KY,Georgetown,120,True,False,True,Electric,2018,Jan
300284,628b89c27b7633e93a2abe430b726e3018266a4a,2018-01-08 11:40:00 UTC,heat,hold,662,670,670,KY,Georgetown,120,False,False,True,Electric,2018,Jan
300285,628b89c27b7633e93a2abe430b726e3018266a4a,2018-01-30 18:45:00 UTC,heat,hold,601,650,600,KY,Georgetown,120,False,False,True,Electric,2018,Jan
300286,1284a01c8a2c0320c4d7a69983a5e2e33658f3ce,2018-01-18 17:30:00 UTC,heat,auto,661,680,680,KY,Georgetown,120,True,False,True,Electric,2018,Jan

In [10]:
jan_2018_ave = jan_2018.groupby(['Identifier', 'Month', 'Year','HvacMode','CalendarEvent', 'City']).mean()

# jan_2018_ave

In [11]:
# Export CSV file

jan_2018_ave.to_csv("data/day/KY/jan/jan_2018_ave.csv", header=True, index=True)

### 2019 January Day

In [12]:
# Read in month csv for state
jan_2019 = pd.read_csv("../data_large/KY-day/2019-jan-day-KY.csv")

# jan_2019

In [13]:
# Add year and month

jan_2019["Year"] = "2019"
jan_2019["Month"] = "Jan"

In [14]:
# Rename columns to label the aggregates

jan_2019.rename(columns={"Temperature_ctrl":"Temperature_ctrl_ave", 
                         "TemperatureExpectedCool":"TemperatureExpectedCool_ave", 
                         "TemperatureExpectedHeat":"TemperatureExpectedHeat_ave"})

,Identifier,date_time,HvacMode,CalendarEvent,Temperature_ctrl_ave,TemperatureExpectedCool_ave,TemperatureExpectedHeat_ave,ProvinceState,City,Age_of_Home__years_,allowCompWithAux,Has_Electric,Has_a_Heat_Pump,Auxilliary_Heat_Fuel_Type,Year,Month
0,3d0e9a4e04c2fee543eef7b52013cf815ae50345,2019-01-05 18:55:00 UTC,auto,hold,694,770,700,KY,Wilmore,118,True,False,True,Electric,2019,Jan
1,c2c20f09a15771decb656a0e7fd0be6f529101cd,2019-01-20 16:30:00 UTC,heat,auto,695,690,690,KY,Vine Grove,28,True,False,True,Electric,2019,Jan
2,a85176f7816955f77859fb3fbc12843017170f61,2019-01-14 12:15:00 UTC,auto,hold,696,770,700,KY,Newport,110,False,False,False,Gas,2019,Jan
3,a85176f7816955f77859fb3fbc12843017170f61,2019-01-27 14:55:00 UTC,auto,hold,719,790,710,KY,Newport,110,False,False,False,Gas,2019,Jan
4,00105867bef9463f0a62d5257d0e91b8c8d19dee,2019-01-26 16:45:00 UTC,heat,hold,645,650,640,KY,Southgate,75,False,False,False,Gas,2019,Jan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
484766,628b89c27b7633e93a2abe430b726e3018266a4a,2019-01-01 15:15:00 UTC,heat,hold,686,690,690,KY,Georgetown,120,False,False,True,Electric,2019,Jan
484767,1284a01c8a2c0320c4d7a69983a5e2e33658f3ce,2019-01-30 11:05:00 UTC,heat,hold,673,670,670,KY,Georgetown,120,True,False,True,Electric,2019,Jan
484768,1284a01c8a2c0320c4d7a69983a5e2e33658f3ce,2019-01-24 16:40:00 UTC,heat,hold,693,700,700,KY,Georgetown,120,True,False,True,Electric,2019,Jan
484769,628b89c27b7633e93a2abe430b726e3018266a4a,2019-01-24 15:35:00 UTC,heat,hold,683,700,700,KY,Georgetown,120,False,False,True,Electric,2019,Jan
484770,1284a01c8a2c0320c4d7a69983a5e2e33658f3ce,2019-01-17 11:30:00 UTC,heat,auto,660,660,660,KY,Georgetown,120,True,False,True,Electric,2019,Jan

In [15]:
jan_2019_ave = jan_2019.groupby(['Identifier', 'Month', 'Year','HvacMode','CalendarEvent', 'City']).mean()

# jan_2019_ave

In [16]:
# Export CSV file

jan_2019_ave.to_csv("data/day/KY/jan/jan_2019_ave.csv", header=True, index=True)

### 2020 January Day

In [17]:
# Read in month csv for state
jan_2020 = pd.read_csv("../data_large/KY-day/2020-jan-day-KY.csv")

# jan_2020

In [18]:
# Add year and month

jan_2020["Year"] = "2020"
jan_2020["Month"] = "Jan"

In [19]:
# Rename columns to label the aggregates

jan_2020.rename(columns={"Temperature_ctrl":"Temperature_ctrl_ave", 
                         "TemperatureExpectedCool":"TemperatureExpectedCool_ave", 
                         "TemperatureExpectedHeat":"TemperatureExpectedHeat_ave"})

,Identifier,date_time,HvacMode,CalendarEvent,Temperature_ctrl_ave,TemperatureExpectedCool_ave,TemperatureExpectedHeat_ave,ProvinceState,City,Age_of_Home__years_,allowCompWithAux,Has_Electric,Has_a_Heat_Pump,Auxilliary_Heat_Fuel_Type,Year,Month
0,a85176f7816955f77859fb3fbc12843017170f61,2020-01-25 14:25:00 UTC,heat,auto,684,700,700,KY,Newport,110,False,False,False,Gas,2020,Jan
1,c2c20f09a15771decb656a0e7fd0be6f529101cd,2020-01-18 14:50:00 UTC,heat,hold,685,700,700,KY,Vine Grove,28,True,False,True,Electric,2020,Jan
2,c2c20f09a15771decb656a0e7fd0be6f529101cd,2020-01-19 18:00:00 UTC,heat,auto,687,680,680,KY,Vine Grove,28,True,False,True,Electric,2020,Jan
3,4f4ffa6020a9cb61a4b227fc6a0768e8fa5e8d22,2020-01-02 19:10:00 UTC,heat,auto,681,680,680,KY,Carrollton,19,False,False,False,Gas,2020,Jan
4,c2c20f09a15771decb656a0e7fd0be6f529101cd,2020-01-18 16:05:00 UTC,heat,hold,698,700,700,KY,Vine Grove,28,True,False,True,Electric,2020,Jan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
543087,628b89c27b7633e93a2abe430b726e3018266a4a,2020-01-07 12:40:00 UTC,heat,hold,665,670,670,KY,Georgetown,120,False,False,True,Electric,2020,Jan
543088,628b89c27b7633e93a2abe430b726e3018266a4a,2020-01-17 13:15:00 UTC,heat,hold,672,680,680,KY,Georgetown,120,False,False,True,Electric,2020,Jan
543089,628b89c27b7633e93a2abe430b726e3018266a4a,2020-01-20 19:50:00 UTC,heat,hold,686,700,700,KY,Georgetown,120,False,False,True,Electric,2020,Jan
543090,628b89c27b7633e93a2abe430b726e3018266a4a,2020-01-09 17:15:00 UTC,heat,hold,698,700,700,KY,Georgetown,120,False,False,True,Electric,2020,Jan
543091,628b89c27b7633e93a2abe430b726e3018266a4a,2020-01-22 16:30:00 UTC,heat,hold,663,670,670,KY,Georgetown,120,False,False,True,Electric,2020,Jan

In [20]:
jan_2020_ave = jan_2020.groupby(['Identifier', 'Month', 'Year','HvacMode','CalendarEvent', 'City']).mean()

# jan_2020_ave

In [21]:
# Export CSV file

jan_2020_ave.to_csv("data/day/KY/jan/jan_2020_ave.csv", header=True, index=True)

---

### Combine state CSV Files 
1. Read in files in folders for each state
2. Export as combined CSV

In [22]:
# Create variable for files in directory
files = [f for f in os.listdir("data/day/KY/jan/") if f.endswith(".csv")]

# files

In [23]:
# https://stackoverflow.com/questions/63886787/how-to-create-a-dataframe-from-multiple-csv-files
# InitiKYize and empty dataframe
KY_jan = pd.DataFrame()

# Iterate through files and contents, then concatenate the data into the dataframe
for file in files:
    df = pd.read_csv("data/day/KY/jan/" + file)
    KY_jan = pd.concat([KY_jan, df])
    
KY_jan

,Identifier,Month,Year,HvacMode,CalendarEvent,City,Temperature_ctrl,TemperatureExpectedCool,TemperatureExpectedHeat,Age_of_Home__years_,allowCompWithAux,Has_Electric,Has_a_Heat_Pump
0,008cfa92481086d7def321eeabb85c0d3eb846de,Jan,2017,heat,auto,Campbellsville,690.518519,707.222222,695.703704,5.0,True,False,True
1,020ded524bca03fd8503e9676cbd617ae62f12d4,Jan,2017,auto,auto,Louisville,703.571429,740.250000,710.178571,15.0,False,False,False
2,020ded524bca03fd8503e9676cbd617ae62f12d4,Jan,2017,auto,hold,Louisville,696.992366,741.167939,693.796438,15.0,False,False,False
3,0475b61636d4d1ba679fd87d374f57927081105b,Jan,2017,heat,auto,Independence,673.257713,771.941924,682.733212,20.0,False,False,False
4,0475b61636d4d1ba679fd87d374f57927081105b,Jan,2017,heat,hold,Independence,706.769231,750.000000,748.230769,20.0,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
767,fd8aaf4038f451870fc23ab85245f4ca4a83a354,Jan,2020,auto,hold,Lexington,665.625000,670.500000,630.000000,18.0,False,False,True
768,fefca5ecf57c50c2f337a1de4577dae3d020f2cd,Jan,2020,heat,hold,Lexington,705.733333,720.000000,720.000000,8.0,True,False,True
769,ff1640c73f967b557d8c64dff6f8139a85e71d38,Jan,2020,heat,auto,Georgetown,646.938484,650.000000,648.540773,15.0,True,False,True
770,ff1640c73f967b557d8c64dff6f8139a85e71d38,Jan,2020,heat,hold,Georgetown,694.274809,702.603053,702.404580,15.0,True,False,True
771,ffbcfc7a85b89b45816e8c216f602c018c63777e,Jan,2020,heat,hold,Lexington,690.851064,700.000000,700.000000,5.0,False,False,True

In [24]:
KY_jan.to_csv("Scraper_Output/State_Month/KY_jan.csv", header=True, index=False)

---

## February

---

## March

---

## April

---

## May

---

## June

---

## July

### 2017 July Day

In [25]:
# Read in month csv for state
jul_2017 = pd.read_csv("../data_large/KY-day/2017-jul-day-KY.csv")

# jul_2017

In [26]:
# Add year and month

jul_2017["Year"] = "2017"
jul_2017["Month"] = "jul"

In [27]:
# Rename columns to label the aggregates

jul_2017.rename(columns={"Temperature_ctrl":"Temperature_ctrl_ave", 
                         "TemperatureExpectedCool":"TemperatureExpectedCool_ave", 
                         "TemperatureExpectedHeat":"TemperatureExpectedHeat_ave"})

,Identifier,date_time,HvacMode,CalendarEvent,Temperature_ctrl_ave,TemperatureExpectedCool_ave,TemperatureExpectedHeat_ave,ProvinceState,City,Age_of_Home__years_,allowCompWithAux,Has_Electric,Has_a_Heat_Pump,Auxilliary_Heat_Fuel_Type,Year,Month
0,0f739392cb73489df16d6bd5cce782aa26047ea0,2017-07-01 19:10:00 UTC,auto,auto,754,720,600,KY,Hickman,85,False,False,False,Gas,2017,jul
1,0f739392cb73489df16d6bd5cce782aa26047ea0,2017-07-01 19:35:00 UTC,auto,auto,763,720,600,KY,Hickman,85,False,False,False,Gas,2017,jul
2,00105867bef9463f0a62d5257d0e91b8c8d19dee,2017-07-09 19:00:00 UTC,cool,hold,715,700,700,KY,Southgate,75,False,False,False,Gas,2017,jul
3,0f739392cb73489df16d6bd5cce782aa26047ea0,2017-07-08 17:45:00 UTC,auto,auto,767,750,600,KY,Hickman,85,False,False,False,Gas,2017,jul
4,0f739392cb73489df16d6bd5cce782aa26047ea0,2017-07-08 18:55:00 UTC,auto,auto,775,750,600,KY,Hickman,85,False,False,False,Gas,2017,jul
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234023,441f78bdc893c61cc6bf174cf95fea1fe597fc91,2017-07-05 18:00:00 UTC,cool,hold,748,750,750,KY,Louisville,90,False,False,False,Gas,2017,jul
234024,262c461792e30453d14b0e95ebe729512187b0f4,2017-07-02 15:25:00 UTC,cool,hold,726,720,720,KY,Louisville,90,False,False,False,Gas,2017,jul
234025,7eb6c3424f78bab4592372fd0a430b52146e201e,2017-07-18 15:25:00 UTC,cool,hold,734,730,730,KY,Louisville,90,False,False,False,Gas,2017,jul
234026,441f78bdc893c61cc6bf174cf95fea1fe597fc91,2017-07-20 12:45:00 UTC,cool,auto,734,730,740,KY,Louisville,90,False,False,False,Gas,2017,jul
234027,441f78bdc893c61cc6bf174cf95fea1fe597fc91,2017-07-18 19:05:00 UTC,cool,auto,730,730,740,KY,Louisville,90,False,False,False,Gas,2017,jul

In [28]:
jul_2017_ave = jul_2017.groupby(['Identifier', 'Month', 'Year','HvacMode','CalendarEvent', 'City']).mean()

# jul_2017_ave

In [29]:
# Export CSV file

jul_2017_ave.to_csv("data/day/KY/jul/jul_2017_ave.csv", header=True, index=True)

### 2018 July Day

In [30]:
# Read in month csv for state
jul_2018 = pd.read_csv("../data_large/KY-day/2018-jul-day-KY.csv")

# jul_2018

In [31]:
# Add year and month

jul_2018["Year"] = "2018"
jul_2018["Month"] = "jul"

In [32]:
# Rename columns to label the aggregates

jul_2018.rename(columns={"Temperature_ctrl":"Temperature_ctrl_ave", 
                         "TemperatureExpectedCool":"TemperatureExpectedCool_ave", 
                         "TemperatureExpectedHeat":"TemperatureExpectedHeat_ave"})

,Identifier,date_time,HvacMode,CalendarEvent,Temperature_ctrl_ave,TemperatureExpectedCool_ave,TemperatureExpectedHeat_ave,ProvinceState,City,Age_of_Home__years_,allowCompWithAux,Has_Electric,Has_a_Heat_Pump,Auxilliary_Heat_Fuel_Type,Year,Month
0,cbdb5db5ce0fcdae40f28f81305bfbbfa747dc4c,2018-07-29 10:45:00 UTC,cool,hold,699,700,700,KY,Crestview Hills,38,True,False,True,Electric,2018,jul
1,cbdb5db5ce0fcdae40f28f81305bfbbfa747dc4c,2018-07-29 10:50:00 UTC,cool,hold,699,700,700,KY,Crestview Hills,38,True,False,True,Electric,2018,jul
2,cbdb5db5ce0fcdae40f28f81305bfbbfa747dc4c,2018-07-21 12:30:00 UTC,cool,hold,702,700,700,KY,Crestview Hills,38,True,False,True,Electric,2018,jul
3,cbdb5db5ce0fcdae40f28f81305bfbbfa747dc4c,2018-07-12 12:50:00 UTC,cool,auto,710,710,680,KY,Crestview Hills,38,True,False,True,Electric,2018,jul
4,d117ee90b026d4dc02dbe36b7e9d1d250274bb5d,2018-07-09 10:45:00 UTC,cool,auto,727,730,730,KY,Mt. Washington,47,True,False,True,Electric,2018,jul
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
490679,af074e178c199f0fff346054a7f6c3114bc27bb0,2018-07-04 16:10:00 UTC,auto,hold,730,722,672,KY,Louisville,120,True,False,False,Gas,2018,jul
490680,af074e178c199f0fff346054a7f6c3114bc27bb0,2018-07-04 14:25:00 UTC,auto,hold,727,722,672,KY,Louisville,120,True,False,False,Gas,2018,jul
490681,af074e178c199f0fff346054a7f6c3114bc27bb0,2018-07-02 16:50:00 UTC,auto,hold,741,722,672,KY,Louisville,120,True,False,False,Gas,2018,jul
490682,af074e178c199f0fff346054a7f6c3114bc27bb0,2018-07-03 14:40:00 UTC,auto,hold,724,722,672,KY,Louisville,120,True,False,False,Gas,2018,jul
490683,af074e178c199f0fff346054a7f6c3114bc27bb0,2018-07-02 15:40:00 UTC,auto,auto,736,732,682,KY,Louisville,120,True,False,False,Gas,2018,jul

In [33]:
jul_2018_ave = jul_2018.groupby(['Identifier', 'Month', 'Year','HvacMode','CalendarEvent', 'City']).mean()

# jul_2018_ave

In [34]:
# Export CSV file

jul_2018_ave.to_csv("data/day/KY/jul/jul_2018_ave.csv", header=True, index=True)

### 2019 July Day

In [35]:
# Read in month csv for state
jul_2019 = pd.read_csv("../data_large/KY-day/2019-jul-day-KY.csv")

# jul_2019

In [36]:
# Add year and month

jul_2019["Year"] = "2019"
jul_2019["Month"] = "jul"

In [37]:
# Rename columns to label the aggregates

jul_2019.rename(columns={"Temperature_ctrl":"Temperature_ctrl_ave", 
                         "TemperatureExpectedCool":"TemperatureExpectedCool_ave", 
                         "TemperatureExpectedHeat":"TemperatureExpectedHeat_ave"})

,Identifier,date_time,HvacMode,CalendarEvent,Temperature_ctrl_ave,TemperatureExpectedCool_ave,TemperatureExpectedHeat_ave,ProvinceState,City,Age_of_Home__years_,allowCompWithAux,Has_Electric,Has_a_Heat_Pump,Auxilliary_Heat_Fuel_Type,Year,Month
0,c2c20f09a15771decb656a0e7fd0be6f529101cd,2019-07-30 15:00:00 UTC,cool,auto,695,690,690,KY,Vine Grove,28,True,False,True,Electric,2019,jul
1,0f739392cb73489df16d6bd5cce782aa26047ea0,2019-07-20 13:05:00 UTC,cool,auto,710,710,710,KY,Hickman,85,False,False,False,Gas,2019,jul
2,c2c20f09a15771decb656a0e7fd0be6f529101cd,2019-07-16 14:05:00 UTC,cool,auto,691,690,690,KY,Vine Grove,28,True,False,True,Electric,2019,jul
3,c2c20f09a15771decb656a0e7fd0be6f529101cd,2019-07-16 13:25:00 UTC,cool,auto,696,690,690,KY,Vine Grove,28,True,False,True,Electric,2019,jul
4,0f739392cb73489df16d6bd5cce782aa26047ea0,2019-07-13 12:35:00 UTC,cool,auto,731,730,720,KY,Hickman,85,False,False,False,Gas,2019,jul
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
622258,628b89c27b7633e93a2abe430b726e3018266a4a,2019-07-19 16:55:00 UTC,cool,auto,740,740,740,KY,Georgetown,120,False,False,True,Electric,2019,jul
622259,628b89c27b7633e93a2abe430b726e3018266a4a,2019-07-26 09:45:00 UTC,cool,hold,733,740,740,KY,Georgetown,120,False,False,True,Electric,2019,jul
622260,628b89c27b7633e93a2abe430b726e3018266a4a,2019-07-20 14:15:00 UTC,cool,hold,736,740,740,KY,Georgetown,120,False,False,True,Electric,2019,jul
622261,628b89c27b7633e93a2abe430b726e3018266a4a,2019-07-22 16:35:00 UTC,cool,hold,755,750,750,KY,Georgetown,120,False,False,True,Electric,2019,jul
622262,628b89c27b7633e93a2abe430b726e3018266a4a,2019-07-29 12:35:00 UTC,cool,hold,752,750,750,KY,Georgetown,120,False,False,True,Electric,2019,jul

In [38]:
jul_2019_ave = jul_2019.groupby(['Identifier', 'Month', 'Year','HvacMode','CalendarEvent', 'City']).mean()

# jul_2019_ave

In [39]:
# Export CSV file

jul_2019_ave.to_csv("data/day/KY/jul/jul_2019_ave.csv", header=True, index=True)

### 2020 July Day

In [40]:
# Read in month csv for state
jul_2020 = pd.read_csv("../data_large/KY-day/2020-jul-day-KY.csv")

# jul_2020

In [41]:
# Add year and month

jul_2020["Year"] = "2020"
jul_2020["Month"] = "jul"

In [42]:
# Rename columns to label the aggregates

jul_2020.rename(columns={"Temperature_ctrl":"Temperature_ctrl_ave", 
                         "TemperatureExpectedCool":"TemperatureExpectedCool_ave", 
                         "TemperatureExpectedHeat":"TemperatureExpectedHeat_ave"})

,Identifier,date_time,HvacMode,CalendarEvent,Temperature_ctrl_ave,TemperatureExpectedCool_ave,TemperatureExpectedHeat_ave,ProvinceState,City,Age_of_Home__years_,allowCompWithAux,Has_Electric,Has_a_Heat_Pump,Auxilliary_Heat_Fuel_Type,Year,Month
0,a85176f7816955f77859fb3fbc12843017170f61,2020-07-04 19:00:00 UTC,cool,auto,764,800,600,KY,Newport,110,False,False,False,Gas,2020,jul
1,3ddcf8c99249bbefb2b23450d38a8b3f25dc19a7,2020-07-05 10:55:00 UTC,cool,hold,738,760,760,KY,Highlands,100,False,False,False,Gas,2020,jul
2,3ddcf8c99249bbefb2b23450d38a8b3f25dc19a7,2020-07-01 19:00:00 UTC,auto,auto,719,710,620,KY,Highlands,100,False,False,False,Gas,2020,jul
3,d61a5a18aab25a00f0f96411957106752a9b4c2e,2020-07-22 17:40:00 UTC,cool,hold,705,700,700,KY,Salyersville,39,True,False,True,Electric,2020,jul
4,31ed9378d5a4cc5c6883c1f09c95c15cec33373d,2020-07-26 14:05:00 UTC,cool,auto,687,690,690,KY,Mount Washington,39,False,False,True,Electric,2020,jul
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595532,628b89c27b7633e93a2abe430b726e3018266a4a,2020-07-27 10:05:00 UTC,cool,hold,740,740,740,KY,Georgetown,120,False,False,True,Electric,2020,jul
595533,628b89c27b7633e93a2abe430b726e3018266a4a,2020-07-28 11:55:00 UTC,cool,hold,736,740,740,KY,Georgetown,120,False,False,True,Electric,2020,jul
595534,628b89c27b7633e93a2abe430b726e3018266a4a,2020-07-31 17:15:00 UTC,cool,hold,718,720,720,KY,Georgetown,120,False,False,True,Electric,2020,jul
595535,628b89c27b7633e93a2abe430b726e3018266a4a,2020-07-11 10:30:00 UTC,cool,hold,728,730,730,KY,Georgetown,120,False,False,True,Electric,2020,jul
595536,628b89c27b7633e93a2abe430b726e3018266a4a,2020-07-16 15:15:00 UTC,cool,hold,737,740,740,KY,Georgetown,120,False,False,True,Electric,2020,jul

In [43]:
jul_2020_ave = jul_2020.groupby(['Identifier', 'Month', 'Year','HvacMode','CalendarEvent', 'City']).mean()

# jul_2020_ave

In [44]:
# Export CSV file

jul_2020_ave.to_csv("data/day/KY/jul/jul_2020_ave.csv", header=True, index=True)

---

### Combine state CSV Files 
1. Read in files in folders for each state
2. Export as combined CSV

In [45]:
# Create variable for files in directory
files = [f for f in os.listdir("data/day/KY/jul/") if f.endswith(".csv")]

# files

In [46]:
# https://stackoverflow.com/questions/63886787/how-to-create-a-dataframe-from-multiple-csv-files
# InitiKYize and empty dataframe
KY_jul = pd.DataFrame()

# Iterate through files and contents, then concatenate the data into the dataframe
for file in files:
    df = pd.read_csv("data/day/KY/jul/" + file)
    KY_jul = pd.concat([KY_jul, df])
    
KY_jul

,Identifier,Month,Year,HvacMode,CalendarEvent,City,Temperature_ctrl,TemperatureExpectedCool,TemperatureExpectedHeat,Age_of_Home__years_,allowCompWithAux,Has_Electric,Has_a_Heat_Pump
0,00105867bef9463f0a62d5257d0e91b8c8d19dee,jul,2017,cool,hold,Southgate,715.631579,700.000000,700.000000,75.0,False,False,False
1,008cfa92481086d7def321eeabb85c0d3eb846de,jul,2017,cool,auto,Campbellsville,706.532468,700.058442,680.000000,5.0,True,False,True
2,008cfa92481086d7def321eeabb85c0d3eb846de,jul,2017,cool,hold,Campbellsville,704.132353,695.573529,695.573529,5.0,True,False,True
3,020ded524bca03fd8503e9676cbd617ae62f12d4,jul,2017,auto,hold,Louisville,711.053571,711.455357,600.000000,15.0,False,False,False
4,0475b61636d4d1ba679fd87d374f57927081105b,jul,2017,auto,auto,Independence,763.537634,780.000000,660.000000,20.0,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
715,fd49781b1b98414ed0495e079dd5435a549a7a86,jul,2020,cool,auto,Alexandria,703.779661,694.915254,694.915254,5.0,False,False,True
716,fd49781b1b98414ed0495e079dd5435a549a7a86,jul,2020,cool,hold,Alexandria,700.489496,692.531513,692.531513,5.0,False,False,True
717,fefca5ecf57c50c2f337a1de4577dae3d020f2cd,jul,2020,cool,hold,Lexington,748.763158,725.087719,725.087719,8.0,True,False,True
718,ff1640c73f967b557d8c64dff6f8139a85e71d38,jul,2020,auto,hold,Georgetown,743.889831,745.355932,604.796610,15.0,True,False,True
719,ffbcfc7a85b89b45816e8c216f602c018c63777e,jul,2020,cool,hold,Lexington,724.386207,720.000000,720.000000,5.0,False,False,True

In [47]:
KY_jul.to_csv("Scraper_Output/State_Month/KY_jul.csv", header=True, index=False)

---

## August

---

## September

---

## October

---

## November

---

## December