# DYD Thermostat Data 

## Preprocess

1. Generated CSV file from queries in BigQueary

2. Data separated into states

3. Aggregated the data in Pandas by month

4. Combine 4 years

5. Group by Identifier

In [1]:
# Dependencies
import pandas as pd
import os
import numpy as np
from pathlib import Path
from datetime import datetime

---
## January

### 2017 January Day

In [2]:
# Read in month csv for state
jan_2017 = pd.read_csv("../data_large/TN-day/2017-jan-day-TN.csv")

# jan_2017

In [3]:
# Add year and month

jan_2017["Year"] = "2017"
jan_2017["Month"] = "Jan"

In [4]:
# Rename columns to label the aggregates

jan_2017.rename(columns={"Temperature_ctrl":"Temperature_ctrl_ave", 
                         "TemperatureExpectedCool":"TemperatureExpectedCool_ave", 
                         "TemperatureExpectedHeat":"TemperatureExpectedHeat_ave"})

,Identifier,date_time,HvacMode,CalendarEvent,Temperature_ctrl_ave,TemperatureExpectedCool_ave,TemperatureExpectedHeat_ave,ProvinceState,City,Age_of_Home__years_,allowCompWithAux,Has_Electric,Has_a_Heat_Pump,Auxilliary_Heat_Fuel_Type,Year,Month
0,f2b57877fbd9c90c626d47b5b65f1733563fa284,2017-01-07 15:30:00 UTC,heat,auto,716,720,720,TN,Knoxville,5,False,False,False,Gas,2017,Jan
1,502860376ff414373c0d8f340b97cc7c1708b889,2017-01-30 18:40:00 UTC,auto,auto,679,720,680,TN,Eagleville,5,False,False,True,Electric,2017,Jan
2,13019ff4001aff2078ea9d7cfffd98047dfb17d3,2017-01-31 13:30:00 UTC,auto,auto,678,725,675,TN,Maryville,25,False,False,False,Gas,2017,Jan
3,da018df787b98b3131e935cfe29bfbfd69a077bc,2017-01-06 19:05:00 UTC,heat,hold,649,650,650,TN,Columbia,0,False,False,True,Electric,2017,Jan
4,17767d97cccacfd4b549914d05bc31d868a85191,2017-01-01 14:35:00 UTC,heat,auto,665,650,620,TN,Murfreesboro,5,False,False,True,Electric,2017,Jan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229906,eedcd8a23ae210facc7258cd53ca00396343f1e7,2017-01-29 15:35:00 UTC,auto,hold,685,740,690,TN,Nashville,15,False,False,False,Gas,2017,Jan
229907,eedcd8a23ae210facc7258cd53ca00396343f1e7,2017-01-29 16:30:00 UTC,auto,hold,684,740,690,TN,Nashville,15,False,False,False,Gas,2017,Jan
229908,eedcd8a23ae210facc7258cd53ca00396343f1e7,2017-01-02 19:25:00 UTC,auto,hold,682,730,680,TN,Nashville,15,False,False,False,Gas,2017,Jan
229909,eedcd8a23ae210facc7258cd53ca00396343f1e7,2017-01-07 12:30:00 UTC,auto,hold,673,730,680,TN,Nashville,15,False,False,False,Gas,2017,Jan
229910,eedcd8a23ae210facc7258cd53ca00396343f1e7,2017-01-05 13:55:00 UTC,auto,hold,675,730,680,TN,Nashville,15,False,False,False,Gas,2017,Jan

In [5]:
jan_2017_ave = jan_2017.groupby(['Identifier', 'Month', 'Year','HvacMode','CalendarEvent', 'City']).mean()

# jan_2017_ave

In [6]:
# Export CSV file

jan_2017_ave.to_csv("data/day/TN/jan/jan_2017_ave.csv", header=True, index=True)

### 2018 January Day

In [7]:
# Read in month csv for state
jan_2018 = pd.read_csv("../data_large/TN-day/2018-jan-day-TN.csv")

# jan_2018

In [8]:
# Add year and month

jan_2018["Year"] = "2018"
jan_2018["Month"] = "Jan"

In [9]:
# Rename columns to label the aggregates

jan_2018.rename(columns={"Temperature_ctrl":"Temperature_ctrl_ave", 
                         "TemperatureExpectedCool":"TemperatureExpectedCool_ave", 
                         "TemperatureExpectedHeat":"TemperatureExpectedHeat_ave"})

,Identifier,date_time,HvacMode,CalendarEvent,Temperature_ctrl_ave,TemperatureExpectedCool_ave,TemperatureExpectedHeat_ave,ProvinceState,City,Age_of_Home__years_,allowCompWithAux,Has_Electric,Has_a_Heat_Pump,Auxilliary_Heat_Fuel_Type,Year,Month
0,def4d2f546181ca8a77634f8aabb880285adcb5f,2018-01-17 13:25:00 UTC,auto,auto,646,820,650,TN,Johnson City,0,False,False,False,Gas,2018,Jan
1,c19adba907c5e47ca49242b3a3f1d16394ada583,2018-01-07 16:55:00 UTC,auto,hold,663,780,670,TN,memphis,0,False,False,False,Gas,2018,Jan
2,66781b7faa9d3874eeaa1ebe9c960d08700578bc,2018-01-17 18:10:00 UTC,heat,auto,717,730,730,TN,Cookeville,25,True,False,True,Electric,2018,Jan
3,c228f59c5c7001815da94b239c913889ee4f738b,2018-01-22 15:20:00 UTC,auto,auto,752,825,775,TN,CORDOVA,10,True,False,False,Gas,2018,Jan
4,8c87ccb624725fed2f1490015f04593f70a96fd7,2018-01-17 15:55:00 UTC,heat,hold,634,650,630,TN,Dyersburg,27,True,False,True,Electric,2018,Jan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
781389,5f58cfda6e1406373cd9cdad2e96c80a4e4891a4,2018-01-27 16:35:00 UTC,auto,auto,717,740,690,TN,Thompson's Station,9,True,False,False,Gas,2018,Jan
781390,5f58cfda6e1406373cd9cdad2e96c80a4e4891a4,2018-01-05 18:45:00 UTC,heat,hold,752,750,750,TN,Thompson's Station,9,True,False,False,Gas,2018,Jan
781391,71a80c838c26d0403faca21e6d85025070c94f2c,2018-01-04 19:25:00 UTC,heat,hold,735,740,740,TN,Thompson's Station,0,True,False,True,Electric,2018,Jan
781392,0def9c996ebdfa7e09e06e30b7a7e59362dc9d5d,2018-01-24 16:35:00 UTC,auto,auto,668,780,650,TN,Thompson's Station,7,False,False,False,Gas,2018,Jan
781393,5f58cfda6e1406373cd9cdad2e96c80a4e4891a4,2018-01-04 16:35:00 UTC,heat,auto,759,760,760,TN,Thompson's Station,9,True,False,False,Gas,2018,Jan

In [10]:
jan_2018_ave = jan_2018.groupby(['Identifier', 'Month', 'Year','HvacMode','CalendarEvent', 'City']).mean()

# jan_2018_ave

In [11]:
# Export CSV file

jan_2018_ave.to_csv("data/day/TN/jan/jan_2018_ave.csv", header=True, index=True)

### 2019 January Day

In [12]:
# Read in month csv for state
jan_2019 = pd.read_csv("../data_large/TN-day/2019-jan-day-TN.csv")

# jan_2019

In [13]:
# Add year and month

jan_2019["Year"] = "2019"
jan_2019["Month"] = "Jan"

In [14]:
# Rename columns to label the aggregates

jan_2019.rename(columns={"Temperature_ctrl":"Temperature_ctrl_ave", 
                         "TemperatureExpectedCool":"TemperatureExpectedCool_ave", 
                         "TemperatureExpectedHeat":"TemperatureExpectedHeat_ave"})

,Identifier,date_time,HvacMode,CalendarEvent,Temperature_ctrl_ave,TemperatureExpectedCool_ave,TemperatureExpectedHeat_ave,ProvinceState,City,Age_of_Home__years_,allowCompWithAux,Has_Electric,Has_a_Heat_Pump,Auxilliary_Heat_Fuel_Type,Year,Month
0,c1e577571f9bef6dfff066243ee72f5c3e1999a6,2019-01-23 16:35:00 UTC,auto,hold,714,768,718,TN,Mount Juliet,25,False,False,False,Gas,2019,Jan
1,246822e717b54301dcdd664882192757e97c1e1c,2019-01-26 18:40:00 UTC,heat,auto,669,665,665,TN,Lebanon,20,False,False,False,Gas,2019,Jan
2,850207f1c14124e4313b80300be35854f5b8e6fa,2019-01-06 18:10:00 UTC,auto,auto,652,695,645,TN,Nashville,20,False,False,False,Gas,2019,Jan
3,d9847a826ef57516183197918e6177b1c5c9f351,2019-01-18 13:00:00 UTC,auto,hold,706,742,712,TN,Cleveland,20,True,False,True,Electric,2019,Jan
4,46ca62bd098ce2b85367fad4fe7df4098341ebab,2019-01-14 12:00:00 UTC,heat,hold,694,685,685,TN,Friendsville,30,True,False,True,Electric,2019,Jan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1213898,e84bd77ebe96b87e6f2f2cc8fbf41f0cf5c29fda,2019-01-29 16:15:00 UTC,heat,auto,705,760,710,TN,Franklin,25,False,False,False,Gas,2019,Jan
1213899,2fac988270329b094312571306ec44164ac3ea6c,2019-01-05 19:00:00 UTC,auto,hold,727,760,690,TN,Pigeon Forge,10,True,False,True,Electric,2019,Jan
1213900,94c6ba51a583caa79907a0661facededd27be3a6,2019-01-14 17:45:00 UTC,cool,auto,618,760,600,TN,Jackson,38,False,False,False,Gas,2019,Jan
1213901,b51a531cdbae140dfd195358a9a9747f10f28476,2019-01-10 13:00:00 UTC,auto,hold,706,760,710,TN,Medina,15,False,False,False,Gas,2019,Jan
1213902,69238258ece7495dbe53d055bc6761a906bee229,2019-01-27 15:40:00 UTC,auto,auto,705,760,710,TN,Clarksville,0,False,False,True,Electric,2019,Jan

In [15]:
jan_2019_ave = jan_2019.groupby(['Identifier', 'Month', 'Year','HvacMode','CalendarEvent', 'City']).mean()

# jan_2019_ave

In [16]:
# Export CSV file

jan_2019_ave.to_csv("data/day/TN/jan/jan_2019_ave.csv", header=True, index=True)

### 2020 January Day

In [17]:
# Read in month csv for state
jan_2020 = pd.read_csv("../data_large/TN-day/2020-jan-day-TN.csv")

# jan_2020

In [18]:
# Add year and month

jan_2020["Year"] = "2020"
jan_2020["Month"] = "Jan"

In [19]:
# Rename columns to label the aggregates

jan_2020.rename(columns={"Temperature_ctrl":"Temperature_ctrl_ave", 
                         "TemperatureExpectedCool":"TemperatureExpectedCool_ave", 
                         "TemperatureExpectedHeat":"TemperatureExpectedHeat_ave"})

,Identifier,date_time,HvacMode,CalendarEvent,Temperature_ctrl_ave,TemperatureExpectedCool_ave,TemperatureExpectedHeat_ave,ProvinceState,City,Age_of_Home__years_,allowCompWithAux,Has_Electric,Has_a_Heat_Pump,Auxilliary_Heat_Fuel_Type,Year,Month
0,7918cf8b884ae264bc1159162210e3054a33e96d,2020-01-26 18:55:00 UTC,heat,auto,690,690,690,TN,Church Hill,6,True,False,True,Electric,2020,Jan
1,9cdf192dc5c7da29e292ac285ef8ff4fb861f11e,2020-01-12 10:05:00 UTC,auto,hold,688,700,650,TN,Oak Ridge,28,False,False,False,Gas,2020,Jan
2,5291f70e9f12f7d80b4624ec4add2fc6d61a6f62,2020-01-29 08:10:00 UTC,auto,hold,684,735,685,TN,Manchester,50,True,False,True,Electric,2020,Jan
3,426f6dd48b9eb72d1182acf8e4346b1d44ac8b85,2020-01-15 16:45:00 UTC,auto,auto,700,730,680,TN,Bells,0,True,False,True,Electric,2020,Jan
4,2590ff129e946052cfcf7c8b5680b6b79f8840ec,2020-01-17 14:15:00 UTC,heat,auto,688,690,690,TN,Tusculum,0,False,False,True,Electric,2020,Jan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1365779,94ba48679496aadf23fb387580fc8eebbd64f6b6,2020-01-22 19:10:00 UTC,heat,hold,729,730,730,TN,Thompsons Station,0,True,False,True,Electric,2020,Jan
1365780,2da807f5029782a8e7677d02094423c52bd5b297,2020-01-19 14:15:00 UTC,heat,hold,700,700,700,TN,Thompsons Station,0,False,False,False,Gas,2020,Jan
1365781,ac3329aa1b90433b515d08d6690d8a65280b34f6,2020-01-26 13:35:00 UTC,heat,hold,674,680,680,TN,Thompsons Station,5,False,False,False,Gas,2020,Jan
1365782,04adebc254991a86381911de7c9d269f2c498bbf,2020-01-09 18:40:00 UTC,heat,auto,737,740,740,TN,Thompsons Station,9,False,False,False,Gas,2020,Jan
1365783,0595a0cca77c13f5405c88dbdcf9edbc64df7169,2020-01-15 19:15:00 UTC,heat,hold,739,740,740,TN,Thompsons Station,5,False,False,False,Gas,2020,Jan

In [20]:
jan_2020_ave = jan_2020.groupby(['Identifier', 'Month', 'Year','HvacMode','CalendarEvent', 'City']).mean()

# jan_2020_ave

In [21]:
# Export CSV file

jan_2020_ave.to_csv("data/day/TN/jan/jan_2020_ave.csv", header=True, index=True)

---

### Combine state CSV Files 
1. Read in files in folders for each state
2. Export as combined CSV

In [22]:
# Create variable for files in directory
files = [f for f in os.listdir("data/day/TN/jan/") if f.endswith(".csv")]

# files

In [23]:
# https://stackoverflow.com/questions/63886787/how-to-create-a-dataframe-from-multiple-csv-files
# InitiTNize and empty dataframe
TN_jan = pd.DataFrame()

# Iterate through files and contents, then concatenate the data into the dataframe
for file in files:
    df = pd.read_csv("data/day/TN/jan/" + file)
    TN_jan = pd.concat([TN_jan, df])
    
TN_jan

,Identifier,Month,Year,HvacMode,CalendarEvent,City,Temperature_ctrl,TemperatureExpectedCool,TemperatureExpectedHeat,Age_of_Home__years_,allowCompWithAux,Has_Electric,Has_a_Heat_Pump
0,01691a75c606f8718e28a6b747c4cb9675a9060b,Jan,2017,heat,auto,Collierville,691.250000,690.000000,690.000000,20.0,False,False,False
1,01691a75c606f8718e28a6b747c4cb9675a9060b,Jan,2017,heat,hold,Collierville,673.958565,675.885591,675.885591,20.0,False,False,False
2,03528fd0510ac074f319f4d196f87f0d2b19fc26,Jan,2017,cool,hold,Clarksville,695.650000,713.600000,713.600000,10.0,False,False,True
3,03528fd0510ac074f319f4d196f87f0d2b19fc26,Jan,2017,heat,auto,Clarksville,699.500000,708.000000,708.000000,10.0,False,False,True
4,03528fd0510ac074f319f4d196f87f0d2b19fc26,Jan,2017,heat,hold,Clarksville,695.244393,696.871616,696.849961,10.0,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1992,ff7e0f2e982b085bf01d460db7670249e73af621,Jan,2020,heat,hold,Knoxville,683.347222,687.361111,687.212963,46.0,False,False,True
1993,ff7e608937812d31b26012c64a6fc58ef9e364a2,Jan,2020,heat,hold,Ooltewah,672.138836,668.423150,668.423150,35.0,True,False,False
1994,ff8eb8fa2d95dad875f0fea5d0685ea03ee73961,Jan,2020,heat,hold,Clarksville,693.198201,693.877698,693.877698,5.0,True,False,True
1995,ffed1fbb1ffd47bca87ef2ec871ff17d145285e5,Jan,2020,auto,auto,Chattanooga,656.761702,754.289362,672.438298,81.0,False,False,True
1996,ffed1fbb1ffd47bca87ef2ec871ff17d145285e5,Jan,2020,auto,hold,Chattanooga,634.000000,760.000000,690.000000,81.0,False,False,True

In [24]:
TN_jan.to_csv("Scraper_Output/State_Month/TN_jan.csv", header=True, index=False)

---

## February

---

## March

---

## April

---

## May

---

## June

---

## July

### 2017 July Day

In [25]:
# Read in month csv for state
jul_2017 = pd.read_csv("../data_large/TN-day/2017-jul-day-TN.csv")

# jul_2017

In [26]:
# Add year and month

jul_2017["Year"] = "2017"
jul_2017["Month"] = "jul"

In [27]:
# Rename columns to label the aggregates

jul_2017.rename(columns={"Temperature_ctrl":"Temperature_ctrl_ave", 
                         "TemperatureExpectedCool":"TemperatureExpectedCool_ave", 
                         "TemperatureExpectedHeat":"TemperatureExpectedHeat_ave"})

,Identifier,date_time,HvacMode,CalendarEvent,Temperature_ctrl_ave,TemperatureExpectedCool_ave,TemperatureExpectedHeat_ave,ProvinceState,City,Age_of_Home__years_,allowCompWithAux,Has_Electric,Has_a_Heat_Pump,Auxilliary_Heat_Fuel_Type,Year,Month
0,8ed41841705611a0d554e6b59bb56dad7e298445,2017-07-22 14:10:00 UTC,cool,hold,771,740,740,TN,Franklin,20,False,False,False,Gas,2017,jul
1,660d942e2515ffa320427416d0ecf82187b574f0,2017-07-15 14:15:00 UTC,cool,auto,722,720,660,TN,Spring Hill,15,False,False,False,Gas,2017,jul
2,3ecb939296d9ac5a96455183c9f013a1eddd154d,2017-07-04 17:10:00 UTC,cool,auto,791,780,640,TN,Memphis,5,True,False,False,Gas,2017,jul
3,46c103c8fa403636c1da6e510a0dc9859ebe244f,2017-07-05 14:50:00 UTC,auto,hold,723,720,660,TN,Franklin,20,False,False,False,Gas,2017,jul
4,bb37622e2893d99ea0dc2f70eca323584eb98b1c,2017-07-29 16:35:00 UTC,cool,hold,762,760,760,TN,Lakeland,37,False,False,True,Electric,2017,jul
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
508832,f8e02d36f8f1bc7797898a09a0db818bf6c0a5d6,2017-07-29 19:20:00 UTC,cool,hold,714,710,710,TN,Nashville,0,False,False,False,Gas,2017,jul
508833,f8e02d36f8f1bc7797898a09a0db818bf6c0a5d6,2017-07-11 12:05:00 UTC,auto,hold,713,720,670,TN,Nashville,0,False,False,False,Gas,2017,jul
508834,f8e02d36f8f1bc7797898a09a0db818bf6c0a5d6,2017-07-11 14:45:00 UTC,auto,hold,712,720,670,TN,Nashville,0,False,False,False,Gas,2017,jul
508835,f8e02d36f8f1bc7797898a09a0db818bf6c0a5d6,2017-07-21 15:40:00 UTC,cool,hold,682,670,670,TN,Nashville,0,False,False,False,Gas,2017,jul
508836,f8e02d36f8f1bc7797898a09a0db818bf6c0a5d6,2017-07-10 19:00:00 UTC,cool,hold,722,710,710,TN,Nashville,0,False,False,False,Gas,2017,jul

In [28]:
jul_2017_ave = jul_2017.groupby(['Identifier', 'Month', 'Year','HvacMode','CalendarEvent', 'City']).mean()

# jul_2017_ave

In [29]:
# Export CSV file

jul_2017_ave.to_csv("data/day/TN/jul/jul_2017_ave.csv", header=True, index=True)

### 2018 July Day

In [30]:
# Read in month csv for state
jul_2018 = pd.read_csv("../data_large/TN-day/2018-jul-day-TN.csv")

# jul_2018

In [31]:
# Add year and month

jul_2018["Year"] = "2018"
jul_2018["Month"] = "jul"

In [32]:
# Rename columns to label the aggregates

jul_2018.rename(columns={"Temperature_ctrl":"Temperature_ctrl_ave", 
                         "TemperatureExpectedCool":"TemperatureExpectedCool_ave", 
                         "TemperatureExpectedHeat":"TemperatureExpectedHeat_ave"})

,Identifier,date_time,HvacMode,CalendarEvent,Temperature_ctrl_ave,TemperatureExpectedCool_ave,TemperatureExpectedHeat_ave,ProvinceState,City,Age_of_Home__years_,allowCompWithAux,Has_Electric,Has_a_Heat_Pump,Auxilliary_Heat_Fuel_Type,Year,Month
0,0def9c996ebdfa7e09e06e30b7a7e59362dc9d5d,2018-07-02 12:30:00 UTC,auto,hold,707,700,650,TN,Thompson's Station,7,False,False,False,Gas,2018,jul
1,f5eeadc778a843ea74aa690f2b2075dc758fa0a1,2018-07-12 08:00:00 UTC,cool,auto,700,708,658,TN,Soddy-Daisy,45,False,False,True,Electric,2018,jul
2,188e0510fe4fbbad85a417b74431402dee2664ea,2018-07-15 13:50:00 UTC,cool,auto,722,720,720,TN,Covington,45,True,False,True,Electric,2018,jul
3,f8bfadf83840e394b678803615c61d68b2ab9f8b,2018-07-14 19:10:00 UTC,auto,hold,743,740,680,TN,White House,40,False,False,False,Gas,2018,jul
4,9299b3b5fb92bdd0de1c2f3bfa7febd27e0ca0af,2018-07-26 12:15:00 UTC,auto,hold,723,720,650,TN,Soddy-Daisy,27,False,False,False,Gas,2018,jul
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1136327,359616012ba36d809082f3414b35c7be946b5b0b,2018-07-06 12:55:00 UTC,cool,hold,765,770,770,TN,Thompsons Station,0,True,False,True,Electric,2018,jul
1136328,67d40146cd4d925e7b7b6f614becb7a26b261816,2018-07-21 15:15:00 UTC,cool,auto,767,760,760,TN,Thompsons Station,0,False,False,True,Electric,2018,jul
1136329,359616012ba36d809082f3414b35c7be946b5b0b,2018-07-19 12:35:00 UTC,cool,hold,765,770,770,TN,Thompsons Station,0,True,False,True,Electric,2018,jul
1136330,1f892ee0ffcb5d9188c3720954f6b32090e9ea66,2018-07-21 16:55:00 UTC,cool,hold,684,680,680,TN,Thompsons Station,5,False,False,False,Gas,2018,jul
1136331,ac3329aa1b90433b515d08d6690d8a65280b34f6,2018-07-29 11:45:00 UTC,cool,hold,684,690,690,TN,Thompsons Station,5,False,False,False,Gas,2018,jul

In [33]:
jul_2018_ave = jul_2018.groupby(['Identifier', 'Month', 'Year','HvacMode','CalendarEvent', 'City']).mean()

# jul_2018_ave

In [34]:
# Export CSV file

jul_2018_ave.to_csv("data/day/TN/jul/jul_2018_ave.csv", header=True, index=True)

### 2019 July Day

In [35]:
# Read in month csv for state
jul_2019 = pd.read_csv("../data_large/TN-day/2019-jul-day-TN.csv")

# jul_2019

In [36]:
# Add year and month

jul_2019["Year"] = "2019"
jul_2019["Month"] = "jul"

In [37]:
# Rename columns to label the aggregates

jul_2019.rename(columns={"Temperature_ctrl":"Temperature_ctrl_ave", 
                         "TemperatureExpectedCool":"TemperatureExpectedCool_ave", 
                         "TemperatureExpectedHeat":"TemperatureExpectedHeat_ave"})

,Identifier,date_time,HvacMode,CalendarEvent,Temperature_ctrl_ave,TemperatureExpectedCool_ave,TemperatureExpectedHeat_ave,ProvinceState,City,Age_of_Home__years_,allowCompWithAux,Has_Electric,Has_a_Heat_Pump,Auxilliary_Heat_Fuel_Type,Year,Month
0,ca462020f4bfcf5fc5820c6d3a86b6af6786699d,2019-07-10 18:35:00 UTC,cool,auto,660,671,671,TN,Sweetwater,9,False,False,True,Electric,2019,jul
1,6dbbc4006039f1f9d01220972496f9bfab053641,2019-07-09 17:05:00 UTC,cool,hold,734,725,725,TN,Knoxville,9,True,False,True,Electric,2019,jul
2,d9847a826ef57516183197918e6177b1c5c9f351,2019-07-12 17:40:00 UTC,cool,hold,729,722,722,TN,Cleveland,20,True,False,True,Electric,2019,jul
3,91bb01318831303802537e86477e573aa035ea29,2019-07-02 14:15:00 UTC,cool,auto,783,780,721,TN,goodletsville,70,True,False,True,Electric,2019,jul
4,59a08cf6699235c607602e0545aa1784469de411,2019-07-30 07:10:00 UTC,auto,auto,713,721,671,TN,Johnson City,40,True,False,True,Electric,2019,jul
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1577224,af0ea0d49040c7e2202794b82079122aedc95906,2019-07-07 12:30:00 UTC,cool,hold,766,760,760,TN,Knoxville,70,False,False,False,Gas,2019,jul
1577225,48cd80e39e07e77a8fe18d850f94319e1585f527,2019-07-03 17:00:00 UTC,cool,hold,755,760,760,TN,Knoxville,90,True,False,False,Gas,2019,jul
1577226,48cd80e39e07e77a8fe18d850f94319e1585f527,2019-07-27 16:40:00 UTC,cool,hold,764,760,760,TN,Knoxville,90,True,False,False,Gas,2019,jul
1577227,b58e9cf5bcc4d7e27b88461a759f40855853a4d8,2019-07-08 16:35:00 UTC,cool,auto,763,760,760,TN,Memphis,10,False,False,False,Gas,2019,jul
1577228,71d5fff0cbcc9043ae90cf670674dfa0d54d6033,2019-07-17 12:10:00 UTC,cool,auto,763,760,760,TN,Nashville,25,True,False,False,Gas,2019,jul

In [38]:
jul_2019_ave = jul_2019.groupby(['Identifier', 'Month', 'Year','HvacMode','CalendarEvent', 'City']).mean()

# jul_2019_ave

In [39]:
# Export CSV file

jul_2019_ave.to_csv("data/day/TN/jul/jul_2019_ave.csv", header=True, index=True)

### 2020 July Day

In [40]:
# Read in month csv for state
jul_2020 = pd.read_csv("../data_large/TN-day/2020-jul-day-TN.csv")

# jul_2020

In [41]:
# Add year and month

jul_2020["Year"] = "2020"
jul_2020["Month"] = "jul"

In [42]:
# Rename columns to label the aggregates

jul_2020.rename(columns={"Temperature_ctrl":"Temperature_ctrl_ave", 
                         "TemperatureExpectedCool":"TemperatureExpectedCool_ave", 
                         "TemperatureExpectedHeat":"TemperatureExpectedHeat_ave"})

,Identifier,date_time,HvacMode,CalendarEvent,Temperature_ctrl_ave,TemperatureExpectedCool_ave,TemperatureExpectedHeat_ave,ProvinceState,City,Age_of_Home__years_,allowCompWithAux,Has_Electric,Has_a_Heat_Pump,Auxilliary_Heat_Fuel_Type,Year,Month
0,95c3e0ef5d2160d40bad180147a99fee346cb132,2020-07-14 08:50:00 UTC,cool,hold,712,776,776,TN,Nashville,0,False,False,False,Gas,2020,jul
1,6c22b29949c52e97406c32805b3d534f0c76f324,2020-07-16 09:55:00 UTC,cool,hold,681,685,685,TN,Knoxville,0,False,False,False,Gas,2020,jul
2,16a2fe256adef8dab9386d6c36ba73eea234b765,2020-07-17 18:10:00 UTC,cool,hold,742,739,739,TN,Nashville,10,False,False,False,Gas,2020,jul
3,204d8f2d5444cadfed08f34b0961701510cd46ff,2020-07-26 16:15:00 UTC,auto,hold,714,705,655,TN,Collierville,0,False,False,False,Gas,2020,jul
4,fc8934892241c0af10534da73ba93685423980e9,2020-07-12 14:05:00 UTC,auto,hold,732,735,685,TN,Farragut,19,True,False,False,Gas,2020,jul
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1565526,4686be39dfd50c114e9c9f7fa50d28643b0da71e,2020-07-26 16:45:00 UTC,cool,hold,767,760,760,TN,Nashville,10,False,False,False,Gas,2020,jul
1565527,ff7e608937812d31b26012c64a6fc58ef9e364a2,2020-07-02 14:35:00 UTC,cool,hold,763,760,760,TN,Ooltewah,35,True,False,False,Gas,2020,jul
1565528,226d3751d186c420edd54b6de8fdcc228e16767c,2020-07-19 15:15:00 UTC,cool,auto,754,760,760,TN,Knoxville,5,True,False,True,Electric,2020,jul
1565529,c76aca7b68a4f0014d462071353e949dd8137302,2020-07-06 16:30:00 UTC,cool,hold,761,760,760,TN,Collierville,0,False,False,False,Gas,2020,jul
1565530,ff7e608937812d31b26012c64a6fc58ef9e364a2,2020-07-30 13:05:00 UTC,cool,hold,760,760,760,TN,Ooltewah,35,True,False,False,Gas,2020,jul

In [43]:
jul_2020_ave = jul_2020.groupby(['Identifier', 'Month', 'Year','HvacMode','CalendarEvent', 'City']).mean()

# jul_2020_ave

In [44]:
# Export CSV file

jul_2020_ave.to_csv("data/day/TN/jul/jul_2020_ave.csv", header=True, index=True)

---

### Combine state CSV Files 
1. Read in files in folders for each state
2. Export as combined CSV

In [45]:
# Create variable for files in directory
files = [f for f in os.listdir("data/day/TN/jul/") if f.endswith(".csv")]

# files

In [46]:
# https://stackoverflow.com/questions/63886787/how-to-create-a-dataframe-from-multiple-csv-files
# InitiTNize and empty dataframe
TN_jul = pd.DataFrame()

# Iterate through files and contents, then concatenate the data into the dataframe
for file in files:
    df = pd.read_csv("data/day/TN/jul/" + file)
    TN_jul = pd.concat([TN_jul, df])
    
TN_jul

,Identifier,Month,Year,HvacMode,CalendarEvent,City,Temperature_ctrl,TemperatureExpectedCool,TemperatureExpectedHeat,Age_of_Home__years_,allowCompWithAux,Has_Electric,Has_a_Heat_Pump
0,0113bf09dfae09204aefa3924186bc90a90264e0,jul,2017,cool,hold,Collierville,764.890041,765.636929,749.728216,30.0,False,False,False
1,01691a75c606f8718e28a6b747c4cb9675a9060b,jul,2017,cool,auto,Collierville,765.181373,766.632353,790.000000,20.0,False,False,False
2,01691a75c606f8718e28a6b747c4cb9675a9060b,jul,2017,cool,hold,Collierville,788.257647,789.461569,781.861569,20.0,False,False,False
3,01b244c6278bc022e1b13b3826143b733278d6bb,jul,2017,cool,auto,Knoxville,749.323529,748.676471,668.617647,15.0,False,False,False
4,031c3898c8f66050458f2072a6e88d6513734a5f,jul,2017,cool,hold,College Grove,709.882353,710.000000,710.000000,7.0,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1927,ff7e608937812d31b26012c64a6fc58ef9e364a2,jul,2020,cool,auto,Ooltewah,761.315376,758.316498,758.316498,35.0,True,False,False
1928,ff7e608937812d31b26012c64a6fc58ef9e364a2,jul,2020,cool,hold,Ooltewah,757.122630,753.939573,753.939573,35.0,True,False,False
1929,ff8eb8fa2d95dad875f0fea5d0685ea03ee73961,jul,2020,cool,hold,Clarksville,703.778567,699.536475,699.536475,5.0,True,False,True
1930,ffed1fbb1ffd47bca87ef2ec871ff17d145285e5,jul,2020,auto,auto,Chattanooga,735.211864,725.635593,656.237288,81.0,False,False,True
1931,ffed1fbb1ffd47bca87ef2ec871ff17d145285e5,jul,2020,auto,hold,Chattanooga,738.931373,720.705882,658.019608,81.0,False,False,True

In [47]:
TN_jul.to_csv("Scraper_Output/State_Month/TN_jul.csv", header=True, index=False)

---

## August

---

## September

---

## October

---

## November

---

## December