# DYD Thermostat Data 

## Preprocess

1. Generated CSV file from queries in BigQueary

2. Data separated into states

3. Aggregated the data in Pandas by month

4. Combine 4 years

5. Group by Identifier

In [1]:
# Dependencies
import pandas as pd
import os
import numpy as np
from pathlib import Path
from datetime import datetime

---
## January

### 2017 January Day

In [2]:
# Read in month csv for state
jan_2017 = pd.read_csv("../data_large/KY-day/2017-jan-day-KY.csv")

# jan_2017

In [3]:
# Add year and month

jan_2017["Year"] = "2017"
jan_2017["Month"] = "Jan"

In [4]:
# Rename columns to label the aggregates

jan_2017.rename(columns={"Temperature_ctrl":"Temperature_ctrl_ave", 
                         "TemperatureExpectedCool":"TemperatureExpectedCool_ave", 
                         "TemperatureExpectedHeat":"TemperatureExpectedHeat_ave"})

,Identifier,date_time,HvacMode,CalendarEvent,Temperature_ctrl_ave,TemperatureExpectedCool_ave,TemperatureExpectedHeat_ave,ProvinceState,City,Age_of_Home__years_,allowCompWithAux,Has_Electric,Has_a_Heat_Pump,Auxilliary_Heat_Fuel_Type,Year,Month
0,96a4ef74ea4ae0b41c2902ac436f65ef8260bc24,2017-01-07 16:55:00 UTC,heat,auto,605,780,620,KY,Prospect,46,True,False,True,Electric,2017,Jan
1,96a4ef74ea4ae0b41c2902ac436f65ef8260bc24,2017-01-23 15:20:00 UTC,heat,hold,673,730,640,KY,Prospect,46,True,False,True,Electric,2017,Jan
2,96a4ef74ea4ae0b41c2902ac436f65ef8260bc24,2017-01-06 16:20:00 UTC,heat,auto,628,730,640,KY,Prospect,46,True,False,True,Electric,2017,Jan
3,96a4ef74ea4ae0b41c2902ac436f65ef8260bc24,2017-01-11 17:50:00 UTC,heat,auto,633,730,640,KY,Prospect,46,True,False,True,Electric,2017,Jan
4,96a4ef74ea4ae0b41c2902ac436f65ef8260bc24,2017-01-06 19:40:00 UTC,heat,auto,630,730,640,KY,Prospect,46,True,False,True,Electric,2017,Jan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113212,ed058081234a88c2d304bb87c8c6a24895c46ec0,2017-01-15 14:40:00 UTC,auto,auto,689,807,653,KY,Nicholasville,10,True,False,True,Electric,2017,Jan
113213,ed058081234a88c2d304bb87c8c6a24895c46ec0,2017-01-10 18:25:00 UTC,auto,auto,680,730,670,KY,Nicholasville,10,True,False,True,Electric,2017,Jan
113214,ed058081234a88c2d304bb87c8c6a24895c46ec0,2017-01-12 18:20:00 UTC,auto,auto,700,740,690,KY,Nicholasville,10,True,False,True,Electric,2017,Jan
113215,ed058081234a88c2d304bb87c8c6a24895c46ec0,2017-01-10 19:00:00 UTC,auto,auto,673,730,670,KY,Nicholasville,10,True,False,True,Electric,2017,Jan
113216,ed058081234a88c2d304bb87c8c6a24895c46ec0,2017-01-08 17:45:00 UTC,auto,auto,628,820,640,KY,Nicholasville,10,True,False,True,Electric,2017,Jan

In [5]:
jan_2017_ave = jan_2017.groupby(['Identifier', 'Month', 'Year','HvacMode','CalendarEvent', 'City']).mean()

# jan_2017_ave

In [6]:
# Export CSV file

jan_2017_ave.to_csv("data/day/KY/jan/jan_2017_ave.csv", header=True, index=True)

### 2018 January Day

In [7]:
# Read in month csv for state
jan_2018 = pd.read_csv("../data_large/KY-day/2018-jan-day-KY.csv")

# jan_2018

In [8]:
# Add year and month

jan_2018["Year"] = "2018"
jan_2018["Month"] = "Jan"

In [9]:
# Rename columns to label the aggregates

jan_2018.rename(columns={"Temperature_ctrl":"Temperature_ctrl_ave", 
                         "TemperatureExpectedCool":"TemperatureExpectedCool_ave", 
                         "TemperatureExpectedHeat":"TemperatureExpectedHeat_ave"})

,Identifier,date_time,HvacMode,CalendarEvent,Temperature_ctrl_ave,TemperatureExpectedCool_ave,TemperatureExpectedHeat_ave,ProvinceState,City,Age_of_Home__years_,allowCompWithAux,Has_Electric,Has_a_Heat_Pump,Auxilliary_Heat_Fuel_Type,Year,Month
0,cbdb5db5ce0fcdae40f28f81305bfbbfa747dc4c,2018-01-27 15:40:00 UTC,auto,hold,675,760,680,KY,Crestview Hills,38,True,False,True,Electric,2018,Jan
1,d117ee90b026d4dc02dbe36b7e9d1d250274bb5d,2018-01-03 10:20:00 UTC,heat,auto,677,680,680,KY,Mt. Washington,47,True,False,True,Electric,2018,Jan
2,d117ee90b026d4dc02dbe36b7e9d1d250274bb5d,2018-01-21 14:50:00 UTC,heat,auto,685,650,600,KY,Mt. Washington,47,True,False,True,Electric,2018,Jan
3,56f54fb3fa14bf1c16c79b63de32965c79394dc5,2018-01-06 11:10:00 UTC,auto,auto,691,745,695,KY,Goshen,36,False,False,True,Electric,2018,Jan
4,cbdb5db5ce0fcdae40f28f81305bfbbfa747dc4c,2018-01-25 17:25:00 UTC,auto,hold,680,760,680,KY,Crestview Hills,38,True,False,True,Electric,2018,Jan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300282,1284a01c8a2c0320c4d7a69983a5e2e33658f3ce,2018-01-31 12:30:00 UTC,heat,hold,596,650,600,KY,Georgetown,120,True,False,True,Electric,2018,Jan
300283,1284a01c8a2c0320c4d7a69983a5e2e33658f3ce,2018-01-02 11:20:00 UTC,heat,hold,644,650,640,KY,Georgetown,120,True,False,True,Electric,2018,Jan
300284,628b89c27b7633e93a2abe430b726e3018266a4a,2018-01-08 11:40:00 UTC,heat,hold,662,670,670,KY,Georgetown,120,False,False,True,Electric,2018,Jan
300285,628b89c27b7633e93a2abe430b726e3018266a4a,2018-01-30 18:45:00 UTC,heat,hold,601,650,600,KY,Georgetown,120,False,False,True,Electric,2018,Jan
300286,1284a01c8a2c0320c4d7a69983a5e2e33658f3ce,2018-01-18 17:30:00 UTC,heat,auto,661,680,680,KY,Georgetown,120,True,False,True,Electric,2018,Jan

In [10]:
jan_2018_ave = jan_2018.groupby(['Identifier', 'Month', 'Year','HvacMode','CalendarEvent', 'City']).mean()

# jan_2018_ave

In [11]:
# Export CSV file

jan_2018_ave.to_csv("data/day/KY/jan/jan_2018_ave.csv", header=True, index=True)

### 2019 January Day

In [12]:
# Read in month csv for state
jan_2019 = pd.read_csv("../data_large/KY-day/2019-jan-day-KY.csv")

# jan_2019

In [13]:
# Add year and month

jan_2019["Year"] = "2019"
jan_2019["Month"] = "Jan"

In [14]:
# Rename columns to label the aggregates

jan_2019.rename(columns={"Temperature_ctrl":"Temperature_ctrl_ave", 
                         "TemperatureExpectedCool":"TemperatureExpectedCool_ave", 
                         "TemperatureExpectedHeat":"TemperatureExpectedHeat_ave"})

,Identifier,date_time,HvacMode,CalendarEvent,Temperature_ctrl_ave,TemperatureExpectedCool_ave,TemperatureExpectedHeat_ave,ProvinceState,City,Age_of_Home__years_,allowCompWithAux,Has_Electric,Has_a_Heat_Pump,Auxilliary_Heat_Fuel_Type,Year,Month
0,3d0e9a4e04c2fee543eef7b52013cf815ae50345,2019-01-05 18:55:00 UTC,auto,hold,694,770,700,KY,Wilmore,118,True,False,True,Electric,2019,Jan
1,c2c20f09a15771decb656a0e7fd0be6f529101cd,2019-01-20 16:30:00 UTC,heat,auto,695,690,690,KY,Vine Grove,28,True,False,True,Electric,2019,Jan
2,a85176f7816955f77859fb3fbc12843017170f61,2019-01-14 12:15:00 UTC,auto,hold,696,770,700,KY,Newport,110,False,False,False,Gas,2019,Jan
3,a85176f7816955f77859fb3fbc12843017170f61,2019-01-27 14:55:00 UTC,auto,hold,719,790,710,KY,Newport,110,False,False,False,Gas,2019,Jan
4,00105867bef9463f0a62d5257d0e91b8c8d19dee,2019-01-26 16:45:00 UTC,heat,hold,645,650,640,KY,Southgate,75,False,False,False,Gas,2019,Jan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
484766,628b89c27b7633e93a2abe430b726e3018266a4a,2019-01-01 15:15:00 UTC,heat,hold,686,690,690,KY,Georgetown,120,False,False,True,Electric,2019,Jan
484767,1284a01c8a2c0320c4d7a69983a5e2e33658f3ce,2019-01-30 11:05:00 UTC,heat,hold,673,670,670,KY,Georgetown,120,True,False,True,Electric,2019,Jan
484768,1284a01c8a2c0320c4d7a69983a5e2e33658f3ce,2019-01-24 16:40:00 UTC,heat,hold,693,700,700,KY,Georgetown,120,True,False,True,Electric,2019,Jan
484769,628b89c27b7633e93a2abe430b726e3018266a4a,2019-01-24 15:35:00 UTC,heat,hold,683,700,700,KY,Georgetown,120,False,False,True,Electric,2019,Jan
484770,1284a01c8a2c0320c4d7a69983a5e2e33658f3ce,2019-01-17 11:30:00 UTC,heat,auto,660,660,660,KY,Georgetown,120,True,False,True,Electric,2019,Jan

In [15]:
jan_2019_ave = jan_2019.groupby(['Identifier', 'Month', 'Year','HvacMode','CalendarEvent', 'City']).mean()

# jan_2019_ave

In [16]:
# Export CSV file

jan_2019_ave.to_csv("data/day/KY/jan/jan_2019_ave.csv", header=True, index=True)

### 2020 January Day

In [17]:
# Read in month csv for state
jan_2020 = pd.read_csv("../data_large/KY-day/2020-jan-day-KY.csv")

# jan_2020

In [18]:
# Add year and month

jan_2020["Year"] = "2020"
jan_2020["Month"] = "Jan"

In [19]:
# Rename columns to label the aggregates

jan_2020.rename(columns={"Temperature_ctrl":"Temperature_ctrl_ave", 
                         "TemperatureExpectedCool":"TemperatureExpectedCool_ave", 
                         "TemperatureExpectedHeat":"TemperatureExpectedHeat_ave"})

,Identifier,date_time,HvacMode,CalendarEvent,Temperature_ctrl_ave,TemperatureExpectedCool_ave,TemperatureExpectedHeat_ave,ProvinceState,City,Age_of_Home__years_,allowCompWithAux,Has_Electric,Has_a_Heat_Pump,Auxilliary_Heat_Fuel_Type,Year,Month
0,a85176f7816955f77859fb3fbc12843017170f61,2020-01-25 14:25:00 UTC,heat,auto,684,700,700,KY,Newport,110,False,False,False,Gas,2020,Jan
1,c2c20f09a15771decb656a0e7fd0be6f529101cd,2020-01-18 14:50:00 UTC,heat,hold,685,700,700,KY,Vine Grove,28,True,False,True,Electric,2020,Jan
2,c2c20f09a15771decb656a0e7fd0be6f529101cd,2020-01-19 18:00:00 UTC,heat,auto,687,680,680,KY,Vine Grove,28,True,False,True,Electric,2020,Jan
3,4f4ffa6020a9cb61a4b227fc6a0768e8fa5e8d22,2020-01-02 19:10:00 UTC,heat,auto,681,680,680,KY,Carrollton,19,False,False,False,Gas,2020,Jan
4,c2c20f09a15771decb656a0e7fd0be6f529101cd,2020-01-18 16:05:00 UTC,heat,hold,698,700,700,KY,Vine Grove,28,True,False,True,Electric,2020,Jan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
543087,628b89c27b7633e93a2abe430b726e3018266a4a,2020-01-07 12:40:00 UTC,heat,hold,665,670,670,KY,Georgetown,120,False,False,True,Electric,2020,Jan
543088,628b89c27b7633e93a2abe430b726e3018266a4a,2020-01-17 13:15:00 UTC,heat,hold,672,680,680,KY,Georgetown,120,False,False,True,Electric,2020,Jan
543089,628b89c27b7633e93a2abe430b726e3018266a4a,2020-01-20 19:50:00 UTC,heat,hold,686,700,700,KY,Georgetown,120,False,False,True,Electric,2020,Jan
543090,628b89c27b7633e93a2abe430b726e3018266a4a,2020-01-09 17:15:00 UTC,heat,hold,698,700,700,KY,Georgetown,120,False,False,True,Electric,2020,Jan
543091,628b89c27b7633e93a2abe430b726e3018266a4a,2020-01-22 16:30:00 UTC,heat,hold,663,670,670,KY,Georgetown,120,False,False,True,Electric,2020,Jan

In [20]:
jan_2020_ave = jan_2020.groupby(['Identifier', 'Month', 'Year','HvacMode','CalendarEvent', 'City']).mean()

# jan_2020_ave

In [21]:
# Export CSV file

jan_2020_ave.to_csv("data/day/KY/jan/jan_2020_ave.csv", header=True, index=True)

### 2021 January Day

In [22]:
# Read in month csv for state
jan_2021 = pd.read_csv("../data_large/KY-day/2021-jan-day-KY.csv")

# jan_2021

In [23]:
# Add year and month

jan_2021["Year"] = "2021"
jan_2021["Month"] = "Jan"

In [24]:
# Rename columns to label the aggregates

jan_2021.rename(columns={"Temperature_ctrl":"Temperature_ctrl_ave", 
                         "TemperatureExpectedCool":"TemperatureExpectedCool_ave", 
                         "TemperatureExpectedHeat":"TemperatureExpectedHeat_ave"})

,Identifier,date_time,HvacMode,CalendarEvent,Temperature_ctrl_ave,TemperatureExpectedCool_ave,TemperatureExpectedHeat_ave,ProvinceState,City,Age_of_Home__years_,allowCompWithAux,Has_Electric,Has_a_Heat_Pump,Auxilliary_Heat_Fuel_Type,Year,Month
0,56f54fb3fa14bf1c16c79b63de32965c79394dc5,2021-01-26 19:15:00 UTC,heat,hold,683,680,680,KY,Goshen,36,False,False,True,Electric,2021,Jan
1,56f54fb3fa14bf1c16c79b63de32965c79394dc5,2021-01-22 19:10:00 UTC,heat,hold,677,680,680,KY,Goshen,36,False,False,True,Electric,2021,Jan
2,3ddcf8c99249bbefb2b23450d38a8b3f25dc19a7,2021-01-02 17:00:00 UTC,heat,hold,682,680,680,KY,Highlands,100,False,False,False,Gas,2021,Jan
3,31ed9378d5a4cc5c6883c1f09c95c15cec33373d,2021-01-20 18:45:00 UTC,heat,hold,690,695,695,KY,Mount Washington,39,False,False,True,Electric,2021,Jan
4,00105867bef9463f0a62d5257d0e91b8c8d19dee,2021-01-17 14:50:00 UTC,heat,hold,675,700,700,KY,Southgate,75,False,False,False,Gas,2021,Jan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
309051,628b89c27b7633e93a2abe430b726e3018266a4a,2021-01-17 18:35:00 UTC,heat,hold,703,710,710,KY,Georgetown,120,False,False,True,Electric,2021,Jan
309052,628b89c27b7633e93a2abe430b726e3018266a4a,2021-01-25 16:00:00 UTC,heat,hold,698,700,700,KY,Georgetown,120,False,False,True,Electric,2021,Jan
309053,628b89c27b7633e93a2abe430b726e3018266a4a,2021-01-16 18:15:00 UTC,heat,hold,707,710,710,KY,Georgetown,120,False,False,True,Electric,2021,Jan
309054,628b89c27b7633e93a2abe430b726e3018266a4a,2021-01-13 16:50:00 UTC,heat,hold,692,690,690,KY,Georgetown,120,False,False,True,Electric,2021,Jan
309055,628b89c27b7633e93a2abe430b726e3018266a4a,2021-01-25 13:15:00 UTC,heat,hold,692,700,700,KY,Georgetown,120,False,False,True,Electric,2021,Jan

In [25]:
jan_2021_ave = jan_2021.groupby(['Identifier', 'Month', 'Year','HvacMode','CalendarEvent', 'City']).mean()

# jan_2021_ave

In [26]:
# Export CSV file

jan_2021_ave.to_csv("data/day/KY/jan/jan_2021_ave.csv", header=True, index=True)

---

### Combine month CSV Files 
1. Read in files in folders for each state
2. Export as combined CSV

In [27]:
# Create variable for files in directory
files = [f for f in os.listdir("data/day/KY/jan/") if f.endswith(".csv")]

# files

In [28]:
# https://stackoverflow.com/questions/63886787/how-to-create-a-dataframe-from-multiple-csv-files
# InitiKYize and empty dataframe
KY_jan = pd.DataFrame()

# Iterate through files and contents, then concatenate the data into the dataframe
for file in files:
    df = pd.read_csv("data/day/KY/jan/" + file)
    KY_jan = pd.concat([KY_jan, df])
    
KY_jan

,Identifier,Month,Year,HvacMode,CalendarEvent,City,Temperature_ctrl,TemperatureExpectedCool,TemperatureExpectedHeat,Age_of_Home__years_,allowCompWithAux,Has_Electric,Has_a_Heat_Pump
0,008cfa92481086d7def321eeabb85c0d3eb846de,Jan,2017,heat,auto,Campbellsville,690.518519,707.222222,695.703704,5.0,True,False,True
1,020ded524bca03fd8503e9676cbd617ae62f12d4,Jan,2017,auto,auto,Louisville,703.571429,740.250000,710.178571,15.0,False,False,False
2,020ded524bca03fd8503e9676cbd617ae62f12d4,Jan,2017,auto,hold,Louisville,696.992366,741.167939,693.796438,15.0,False,False,False
3,0475b61636d4d1ba679fd87d374f57927081105b,Jan,2017,heat,auto,Independence,673.257713,771.941924,682.733212,20.0,False,False,False
4,0475b61636d4d1ba679fd87d374f57927081105b,Jan,2017,heat,hold,Independence,706.769231,750.000000,748.230769,20.0,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
369,fbc6ca24b330ad08582428e1e6c4b41ada6665ba,Jan,2021,heat,hold,Glasgow,725.780488,736.926829,734.585366,60.0,False,False,False
370,fbdfee9610a20af314ae084b9e6b9f48c07e0fc2,Jan,2021,heat,hold,Louisville,697.044994,699.695817,699.695817,45.0,False,False,False
371,fca3aecc617d455ff79c8654219bbc7628348f90,Jan,2021,heat,hold,Whitley City,710.460000,716.260000,715.580000,0.0,True,False,False
372,fd49781b1b98414ed0495e079dd5435a549a7a86,Jan,2021,heat,hold,Alexandria,685.934104,690.113873,690.113873,5.0,False,False,True
373,ff1640c73f967b557d8c64dff6f8139a85e71d38,Jan,2021,auto,hold,Georgetown,665.528875,743.413374,669.420973,15.0,True,False,True

In [29]:
KY_jan.to_csv("Scraper_Output/State_Month_Day/KY/KY_jan.csv", header=True, index=False)

---

## February

### 2017 February Day

In [30]:
# Read in month csv for state
feb_2017 = pd.read_csv("../data_large/KY-day/2017-feb-day-KY.csv")

# feb_2017

In [31]:
# Add year and month

feb_2017["Year"] = "2017"
feb_2017["Month"] = "feb"

In [32]:
# Rename columns to label the aggregates

feb_2017.rename(columns={"Temperature_ctrl":"Temperature_ctrl_ave", 
                         "TemperatureExpectedCool":"TemperatureExpectedCool_ave", 
                         "TemperatureExpectedHeat":"TemperatureExpectedHeat_ave"})

,Identifier,date_time,HvacMode,CalendarEvent,Temperature_ctrl_ave,TemperatureExpectedCool_ave,TemperatureExpectedHeat_ave,ProvinceState,City,Age_of_Home__years_,allowCompWithAux,Has_Electric,Has_a_Heat_Pump,Auxilliary_Heat_Fuel_Type,Year,Month
0,56f54fb3fa14bf1c16c79b63de32965c79394dc5,2017-02-24 11:15:00 UTC,auto,auto,683,715,665,KY,Goshen,36,False,False,True,Electric,2017,feb
1,56f54fb3fa14bf1c16c79b63de32965c79394dc5,2017-02-23 11:30:00 UTC,auto,auto,680,715,665,KY,Goshen,36,False,False,True,Electric,2017,feb
2,56f54fb3fa14bf1c16c79b63de32965c79394dc5,2017-02-23 11:05:00 UTC,auto,auto,680,715,665,KY,Goshen,36,False,False,True,Electric,2017,feb
3,56f54fb3fa14bf1c16c79b63de32965c79394dc5,2017-02-23 11:25:00 UTC,auto,auto,680,715,665,KY,Goshen,36,False,False,True,Electric,2017,feb
4,56f54fb3fa14bf1c16c79b63de32965c79394dc5,2017-02-23 11:45:00 UTC,auto,auto,682,715,665,KY,Goshen,36,False,False,True,Electric,2017,feb
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110642,93a99c8c1f855b66361b16e00f1ea69f13216c11,2017-02-16 17:45:00 UTC,auto,hold,695,780,700,KY,Lexington,90,False,False,False,Gas,2017,feb
110643,93a99c8c1f855b66361b16e00f1ea69f13216c11,2017-02-02 19:55:00 UTC,auto,hold,706,780,700,KY,Lexington,90,False,False,False,Gas,2017,feb
110644,93a99c8c1f855b66361b16e00f1ea69f13216c11,2017-02-08 14:35:00 UTC,auto,hold,693,780,680,KY,Lexington,90,False,False,False,Gas,2017,feb
110645,93a99c8c1f855b66361b16e00f1ea69f13216c11,2017-02-22 17:10:00 UTC,auto,hold,713,780,690,KY,Lexington,90,False,False,False,Gas,2017,feb
110646,93a99c8c1f855b66361b16e00f1ea69f13216c11,2017-02-20 19:50:00 UTC,auto,hold,709,780,690,KY,Lexington,90,False,False,False,Gas,2017,feb

In [33]:
feb_2017_ave = feb_2017.groupby(['Identifier', 'Month', 'Year','HvacMode','CalendarEvent', 'City']).mean()

# feb_2017_ave

In [34]:
# Export CSV file

feb_2017_ave.to_csv("data/day/KY/feb/feb_2017_ave.csv", header=True, index=True)

### 2018 February Day

In [35]:
# Read in month csv for state
feb_2018 = pd.read_csv("../data_large/KY-day/2018-feb-day-KY.csv")

# feb_2018

In [36]:
# Add year and month

feb_2018["Year"] = "2018"
feb_2018["Month"] = "feb"

In [37]:
# Rename columns to label the aggregates

feb_2018.rename(columns={"Temperature_ctrl":"Temperature_ctrl_ave", 
                         "TemperatureExpectedCool":"TemperatureExpectedCool_ave", 
                         "TemperatureExpectedHeat":"TemperatureExpectedHeat_ave"})

,Identifier,date_time,HvacMode,CalendarEvent,Temperature_ctrl_ave,TemperatureExpectedCool_ave,TemperatureExpectedHeat_ave,ProvinceState,City,Age_of_Home__years_,allowCompWithAux,Has_Electric,Has_a_Heat_Pump,Auxilliary_Heat_Fuel_Type,Year,Month
0,cbdb5db5ce0fcdae40f28f81305bfbbfa747dc4c,2018-02-22 19:20:00 UTC,auto,hold,684,760,680,KY,Crestview Hills,38,True,False,True,Electric,2018,feb
1,3d0e9a4e04c2fee543eef7b52013cf815ae50345,2018-02-23 09:55:00 UTC,auto,hold,675,820,680,KY,Wilmore,118,True,False,True,Electric,2018,feb
2,cbdb5db5ce0fcdae40f28f81305bfbbfa747dc4c,2018-02-13 14:55:00 UTC,heat,auto,690,760,690,KY,Crestview Hills,38,True,False,True,Electric,2018,feb
3,cbdb5db5ce0fcdae40f28f81305bfbbfa747dc4c,2018-02-19 17:15:00 UTC,auto,auto,690,760,690,KY,Crestview Hills,38,True,False,True,Electric,2018,feb
4,3d0e9a4e04c2fee543eef7b52013cf815ae50345,2018-02-04 19:15:00 UTC,auto,hold,668,770,680,KY,Wilmore,118,True,False,True,Electric,2018,feb
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
288142,af074e178c199f0fff346054a7f6c3114bc27bb0,2018-02-18 12:15:00 UTC,auto,hold,646,780,650,KY,Louisville,120,True,False,False,Gas,2018,feb
288143,af074e178c199f0fff346054a7f6c3114bc27bb0,2018-02-27 17:00:00 UTC,auto,hold,624,780,450,KY,Louisville,120,True,False,False,Gas,2018,feb
288144,af074e178c199f0fff346054a7f6c3114bc27bb0,2018-02-27 15:15:00 UTC,auto,hold,608,780,450,KY,Louisville,120,True,False,False,Gas,2018,feb
288145,af074e178c199f0fff346054a7f6c3114bc27bb0,2018-02-26 17:05:00 UTC,auto,hold,617,780,450,KY,Louisville,120,True,False,False,Gas,2018,feb
288146,af074e178c199f0fff346054a7f6c3114bc27bb0,2018-02-26 19:35:00 UTC,auto,hold,613,780,450,KY,Louisville,120,True,False,False,Gas,2018,feb

In [38]:
feb_2018_ave = feb_2018.groupby(['Identifier', 'Month', 'Year','HvacMode','CalendarEvent', 'City']).mean()

# feb_2018_ave

In [39]:
# Export CSV file

feb_2018_ave.to_csv("data/day/KY/feb/feb_2018_ave.csv", header=True, index=True)

### 2019 February Day

In [40]:
# Read in month csv for state
feb_2019 = pd.read_csv("../data_large/KY-day/2019-feb-day-KY.csv")

# feb_2019

In [41]:
# Add year and month

feb_2019["Year"] = "2019"
feb_2019["Month"] = "feb"

In [42]:
# Rename columns to label the aggregates

feb_2019.rename(columns={"Temperature_ctrl":"Temperature_ctrl_ave", 
                         "TemperatureExpectedCool":"TemperatureExpectedCool_ave", 
                         "TemperatureExpectedHeat":"TemperatureExpectedHeat_ave"})

,Identifier,date_time,HvacMode,CalendarEvent,Temperature_ctrl_ave,TemperatureExpectedCool_ave,TemperatureExpectedHeat_ave,ProvinceState,City,Age_of_Home__years_,allowCompWithAux,Has_Electric,Has_a_Heat_Pump,Auxilliary_Heat_Fuel_Type,Year,Month
0,c2c20f09a15771decb656a0e7fd0be6f529101cd,2019-02-22 11:25:00 UTC,heat,auto,684,680,680,KY,Vine Grove,28,True,False,True,Electric,2019,feb
1,a85176f7816955f77859fb3fbc12843017170f61,2019-02-02 15:35:00 UTC,auto,hold,711,780,720,KY,Newport,110,False,False,False,Gas,2019,feb
2,c2c20f09a15771decb656a0e7fd0be6f529101cd,2019-02-24 14:35:00 UTC,heat,auto,676,670,670,KY,Vine Grove,28,True,False,True,Electric,2019,feb
3,a85176f7816955f77859fb3fbc12843017170f61,2019-02-23 16:05:00 UTC,auto,hold,704,770,710,KY,Newport,110,False,False,False,Gas,2019,feb
4,a85176f7816955f77859fb3fbc12843017170f61,2019-02-16 16:10:00 UTC,auto,auto,686,750,690,KY,Newport,110,False,False,False,Gas,2019,feb
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
334725,628b89c27b7633e93a2abe430b726e3018266a4a,2019-02-04 10:30:00 UTC,heat,auto,676,680,680,KY,Georgetown,120,False,False,True,Electric,2019,feb
334726,628b89c27b7633e93a2abe430b726e3018266a4a,2019-02-13 11:55:00 UTC,heat,hold,677,680,680,KY,Georgetown,120,False,False,True,Electric,2019,feb
334727,628b89c27b7633e93a2abe430b726e3018266a4a,2019-02-28 16:15:00 UTC,heat,auto,680,680,680,KY,Georgetown,120,False,False,True,Electric,2019,feb
334728,628b89c27b7633e93a2abe430b726e3018266a4a,2019-02-23 18:45:00 UTC,heat,hold,680,680,680,KY,Georgetown,120,False,False,True,Electric,2019,feb
334729,628b89c27b7633e93a2abe430b726e3018266a4a,2019-02-10 19:10:00 UTC,heat,hold,690,700,700,KY,Georgetown,120,False,False,True,Electric,2019,feb

In [43]:
feb_2019_ave = feb_2019.groupby(['Identifier', 'Month', 'Year','HvacMode','CalendarEvent', 'City']).mean()

# feb_2019_ave

In [44]:
# Export CSV file

feb_2019_ave.to_csv("data/day/KY/feb/feb_2019_ave.csv", header=True, index=True)

### 2020 February Day

In [45]:
# Read in month csv for state
feb_2020 = pd.read_csv("../data_large/KY-day/2020-feb-day-KY.csv")

# feb_2020

In [46]:
# Add year and month

feb_2020["Year"] = "2020"
feb_2020["Month"] = "feb"

In [47]:
# Rename columns to label the aggregates

feb_2020.rename(columns={"Temperature_ctrl":"Temperature_ctrl_ave", 
                         "TemperatureExpectedCool":"TemperatureExpectedCool_ave", 
                         "TemperatureExpectedHeat":"TemperatureExpectedHeat_ave"})

,Identifier,date_time,HvacMode,CalendarEvent,Temperature_ctrl_ave,TemperatureExpectedCool_ave,TemperatureExpectedHeat_ave,ProvinceState,City,Age_of_Home__years_,allowCompWithAux,Has_Electric,Has_a_Heat_Pump,Auxilliary_Heat_Fuel_Type,Year,Month
0,c2c20f09a15771decb656a0e7fd0be6f529101cd,2020-02-20 10:55:00 UTC,heat,auto,674,680,680,KY,Vine Grove,28,True,False,True,Electric,2020,feb
1,a85176f7816955f77859fb3fbc12843017170f61,2020-02-16 15:45:00 UTC,heat,auto,689,710,710,KY,Newport,110,False,False,False,Gas,2020,feb
2,8c1eae3eccaf4af9d9dcaa4e25ddb883d6339700,2020-02-22 16:10:00 UTC,heat,hold,696,700,700,KY,Versailles,39,True,False,True,Electric,2020,feb
3,a85176f7816955f77859fb3fbc12843017170f61,2020-02-02 15:45:00 UTC,heat,auto,653,720,660,KY,Newport,110,False,False,False,Gas,2020,feb
4,3ddcf8c99249bbefb2b23450d38a8b3f25dc19a7,2020-02-25 14:25:00 UTC,heat,hold,648,650,650,KY,Highlands,100,False,False,False,Gas,2020,feb
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
491624,628b89c27b7633e93a2abe430b726e3018266a4a,2020-02-11 19:05:00 UTC,heat,hold,677,680,680,KY,Georgetown,120,False,False,True,Electric,2020,feb
491625,628b89c27b7633e93a2abe430b726e3018266a4a,2020-02-02 15:35:00 UTC,heat,hold,697,700,700,KY,Georgetown,120,False,False,True,Electric,2020,feb
491626,1284a01c8a2c0320c4d7a69983a5e2e33658f3ce,2020-02-27 13:00:00 UTC,heat,hold,671,680,680,KY,Georgetown,120,True,False,True,Electric,2020,feb
491627,1284a01c8a2c0320c4d7a69983a5e2e33658f3ce,2020-02-27 16:25:00 UTC,heat,hold,676,680,680,KY,Georgetown,120,True,False,True,Electric,2020,feb
491628,af074e178c199f0fff346054a7f6c3114bc27bb0,2020-02-27 14:05:00 UTC,auto,auto,690,770,720,KY,Louisville,120,True,False,False,Gas,2020,feb

In [48]:
feb_2020_ave = feb_2020.groupby(['Identifier', 'Month', 'Year','HvacMode','CalendarEvent', 'City']).mean()

# feb_2020_ave

In [49]:
# Export CSV file

feb_2020_ave.to_csv("data/day/KY/feb/feb_2020_ave.csv", header=True, index=True)

### 2021 February Day

In [50]:
# Read in month csv for state
feb_2021 = pd.read_csv("../data_large/KY-day/2021-feb-day-KY.csv")

# feb_2021

In [51]:
# Add year and month

feb_2021["Year"] = "2021"
feb_2021["Month"] = "feb"

In [52]:
# Rename columns to label the aggregates

feb_2021.rename(columns={"Temperature_ctrl":"Temperature_ctrl_ave", 
                         "TemperatureExpectedCool":"TemperatureExpectedCool_ave", 
                         "TemperatureExpectedHeat":"TemperatureExpectedHeat_ave"})

,Identifier,date_time,HvacMode,CalendarEvent,Temperature_ctrl_ave,TemperatureExpectedCool_ave,TemperatureExpectedHeat_ave,ProvinceState,City,Age_of_Home__years_,allowCompWithAux,Has_Electric,Has_a_Heat_Pump,Auxilliary_Heat_Fuel_Type,Year,Month
0,a85176f7816955f77859fb3fbc12843017170f61,2021-02-22 16:10:00 UTC,heat,hold,691,700,700,KY,Newport,110,False,False,False,Gas,2021,feb
1,3ddcf8c99249bbefb2b23450d38a8b3f25dc19a7,2021-02-12 15:20:00 UTC,heat,hold,674,680,680,KY,Highlands,100,False,False,False,Gas,2021,feb
2,3ddcf8c99249bbefb2b23450d38a8b3f25dc19a7,2021-02-08 16:35:00 UTC,heat,hold,675,680,680,KY,Highlands,100,False,False,False,Gas,2021,feb
3,31ed9378d5a4cc5c6883c1f09c95c15cec33373d,2021-02-28 15:20:00 UTC,heat,hold,692,692,692,KY,Mount Washington,39,False,False,True,Electric,2021,feb
4,31ed9378d5a4cc5c6883c1f09c95c15cec33373d,2021-02-26 18:15:00 UTC,heat,hold,678,692,692,KY,Mount Washington,39,False,False,True,Electric,2021,feb
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
280109,628b89c27b7633e93a2abe430b726e3018266a4a,2021-02-21 19:00:00 UTC,heat,hold,694,700,700,KY,Georgetown,120,False,False,True,Electric,2021,feb
280110,628b89c27b7633e93a2abe430b726e3018266a4a,2021-02-05 19:30:00 UTC,heat,hold,684,690,690,KY,Georgetown,120,False,False,True,Electric,2021,feb
280111,628b89c27b7633e93a2abe430b726e3018266a4a,2021-02-01 13:15:00 UTC,heat,hold,687,700,700,KY,Georgetown,120,False,False,True,Electric,2021,feb
280112,628b89c27b7633e93a2abe430b726e3018266a4a,2021-02-15 16:00:00 UTC,heat,hold,680,690,690,KY,Georgetown,120,False,False,True,Electric,2021,feb
280113,628b89c27b7633e93a2abe430b726e3018266a4a,2021-02-20 14:25:00 UTC,heat,hold,695,690,690,KY,Georgetown,120,False,False,True,Electric,2021,feb

In [53]:
feb_2021_ave = feb_2021.groupby(['Identifier', 'Month', 'Year','HvacMode','CalendarEvent', 'City']).mean()

# feb_2021_ave

In [54]:
# Export CSV file

feb_2021_ave.to_csv("data/day/KY/feb/feb_2021_ave.csv", header=True, index=True)

---

### Combine month CSV Files 
1. Read in files in folders for each state
2. Export as combined CSV

In [55]:
# Create variable for files in directory
files = [f for f in os.listdir("data/day/KY/feb/") if f.endswith(".csv")]

# files

In [56]:
# https://stackoverflow.com/questions/63886787/how-to-create-a-dataframe-from-multiple-csv-files
# InitiKYize and empty dataframe
KY_feb = pd.DataFrame()

# Iterate through files and contents, then concatenate the data into the dataframe
for file in files:
    df = pd.read_csv("data/day/KY/feb/" + file)
    KY_feb = pd.concat([KY_feb, df])
    
KY_feb

,Identifier,Month,Year,HvacMode,CalendarEvent,City,Temperature_ctrl,TemperatureExpectedCool,TemperatureExpectedHeat,Age_of_Home__years_,allowCompWithAux,Has_Electric,Has_a_Heat_Pump
0,008cfa92481086d7def321eeabb85c0d3eb846de,feb,2017,auto,auto,Campbellsville,699.600000,699.750000,679.750000,5.0,True,False,True
1,008cfa92481086d7def321eeabb85c0d3eb846de,feb,2017,auto,hold,Campbellsville,698.333333,680.000000,660.000000,5.0,True,False,True
2,008cfa92481086d7def321eeabb85c0d3eb846de,feb,2017,heat,auto,Campbellsville,699.305556,700.166667,699.833333,5.0,True,False,True
3,020ded524bca03fd8503e9676cbd617ae62f12d4,feb,2017,auto,hold,Louisville,697.160171,734.989322,690.764015,15.0,False,False,False
4,0475b61636d4d1ba679fd87d374f57927081105b,feb,2017,heat,auto,Independence,677.318182,771.586364,682.754545,20.0,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
385,fbdfee9610a20af314ae084b9e6b9f48c07e0fc2,feb,2021,heat,hold,Louisville,697.073493,700.000000,700.000000,45.0,False,False,False
386,fca3aecc617d455ff79c8654219bbc7628348f90,feb,2021,heat,hold,Whitley City,708.562500,715.500000,714.666667,0.0,True,False,False
387,fd49781b1b98414ed0495e079dd5435a549a7a86,feb,2021,heat,hold,Alexandria,685.110897,687.702025,687.702025,5.0,False,False,True
388,ff1640c73f967b557d8c64dff6f8139a85e71d38,feb,2021,auto,hold,Georgetown,691.000000,730.000000,710.000000,15.0,True,False,True
389,ffbcfc7a85b89b45816e8c216f602c018c63777e,feb,2021,auto,hold,Lexington,680.224490,757.326531,707.326531,5.0,False,False,True

In [57]:
KY_feb.to_csv("Scraper_Output/State_Month_Day/KY/KY_feb.csv", header=True, index=False)

---

## March

---

## April

---

## May

---

## June

### 2017 June Day

In [58]:
# Read in month csv for state
jun_2017 = pd.read_csv("../data_large/KY-day/2017-jun-day-KY.csv")

# jun_2017

In [59]:
# Add year and month

jun_2017["Year"] = "2017"
jun_2017["Month"] = "jun"

In [60]:
# Rename columns to label the aggregates

jun_2017.rename(columns={"Temperature_ctrl":"Temperature_ctrl_ave", 
                         "TemperatureExpectedCool":"TemperatureExpectedCool_ave", 
                         "TemperatureExpectedHeat":"TemperatureExpectedHeat_ave"})

,Identifier,date_time,HvacMode,CalendarEvent,Temperature_ctrl_ave,TemperatureExpectedCool_ave,TemperatureExpectedHeat_ave,ProvinceState,City,Age_of_Home__years_,allowCompWithAux,Has_Electric,Has_a_Heat_Pump,Auxilliary_Heat_Fuel_Type,Year,Month
0,0f739392cb73489df16d6bd5cce782aa26047ea0,2017-06-10 17:45:00 UTC,auto,auto,741,710,600,KY,Hickman,85,False,False,False,Gas,2017,jun
1,0f739392cb73489df16d6bd5cce782aa26047ea0,2017-06-10 16:45:00 UTC,auto,auto,747,710,600,KY,Hickman,85,False,False,False,Gas,2017,jun
2,0f739392cb73489df16d6bd5cce782aa26047ea0,2017-06-17 19:45:00 UTC,auto,auto,778,710,600,KY,Hickman,85,False,False,False,Gas,2017,jun
3,0f739392cb73489df16d6bd5cce782aa26047ea0,2017-06-25 18:45:00 UTC,auto,auto,781,720,600,KY,Hickman,85,False,False,False,Gas,2017,jun
4,0f739392cb73489df16d6bd5cce782aa26047ea0,2017-06-25 19:10:00 UTC,auto,auto,778,720,600,KY,Hickman,85,False,False,False,Gas,2017,jun
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197830,262c461792e30453d14b0e95ebe729512187b0f4,2017-06-18 11:05:00 UTC,cool,hold,724,720,720,KY,Louisville,90,False,False,False,Gas,2017,jun
197831,441f78bdc893c61cc6bf174cf95fea1fe597fc91,2017-06-09 11:00:00 UTC,cool,hold,700,740,740,KY,Louisville,90,False,False,False,Gas,2017,jun
197832,262c461792e30453d14b0e95ebe729512187b0f4,2017-06-19 17:00:00 UTC,cool,auto,752,760,720,KY,Louisville,90,False,False,False,Gas,2017,jun
197833,262c461792e30453d14b0e95ebe729512187b0f4,2017-06-08 18:10:00 UTC,cool,hold,712,729,729,KY,Louisville,90,False,False,False,Gas,2017,jun
197834,df93077f04f2403ad7e0a12bce9f526332cc3cc1,2017-06-22 15:15:00 UTC,cool,auto,739,740,720,KY,Louisville,90,False,False,False,Gas,2017,jun

In [61]:
jun_2017_ave = jun_2017.groupby(['Identifier', 'Month', 'Year','HvacMode','CalendarEvent', 'City']).mean()

# jun_2017_ave

In [62]:
# Export CSV file

jun_2017_ave.to_csv("data/day/KY/jun/jun_2017_ave.csv", header=True, index=True)

### 2018 June Day

In [63]:
# Read in month csv for state
jun_2018 = pd.read_csv("../data_large/KY-day/2018-jun-day-KY.csv")

# jun_2018

In [64]:
# Add year and month

jun_2018["Year"] = "2018"
jun_2018["Month"] = "jun"

In [65]:
# Rename columns to label the aggregates

jun_2018.rename(columns={"Temperature_ctrl":"Temperature_ctrl_ave", 
                         "TemperatureExpectedCool":"TemperatureExpectedCool_ave", 
                         "TemperatureExpectedHeat":"TemperatureExpectedHeat_ave"})

,Identifier,date_time,HvacMode,CalendarEvent,Temperature_ctrl_ave,TemperatureExpectedCool_ave,TemperatureExpectedHeat_ave,ProvinceState,City,Age_of_Home__years_,allowCompWithAux,Has_Electric,Has_a_Heat_Pump,Auxilliary_Heat_Fuel_Type,Year,Month
0,cbdb5db5ce0fcdae40f28f81305bfbbfa747dc4c,2018-06-19 11:05:00 UTC,cool,hold,722,720,720,KY,Crestview Hills,38,True,False,True,Electric,2018,jun
1,d117ee90b026d4dc02dbe36b7e9d1d250274bb5d,2018-06-18 17:05:00 UTC,cool,auto,726,720,720,KY,Mt. Washington,47,True,False,True,Electric,2018,jun
2,d117ee90b026d4dc02dbe36b7e9d1d250274bb5d,2018-06-02 16:35:00 UTC,cool,hold,709,700,700,KY,Mt. Washington,47,True,False,True,Electric,2018,jun
3,a85176f7816955f77859fb3fbc12843017170f61,2018-06-16 18:05:00 UTC,auto,auto,681,680,620,KY,Newport,110,False,False,False,Gas,2018,jun
4,cbdb5db5ce0fcdae40f28f81305bfbbfa747dc4c,2018-06-23 18:25:00 UTC,cool,hold,701,700,700,KY,Crestview Hills,38,True,False,True,Electric,2018,jun
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
426855,af074e178c199f0fff346054a7f6c3114bc27bb0,2018-06-15 12:00:00 UTC,auto,hold,711,712,662,KY,Louisville,120,True,False,False,Gas,2018,jun
426856,af074e178c199f0fff346054a7f6c3114bc27bb0,2018-06-16 12:30:00 UTC,auto,hold,717,712,662,KY,Louisville,120,True,False,False,Gas,2018,jun
426857,af074e178c199f0fff346054a7f6c3114bc27bb0,2018-06-22 17:00:00 UTC,auto,hold,715,712,662,KY,Louisville,120,True,False,False,Gas,2018,jun
426858,af074e178c199f0fff346054a7f6c3114bc27bb0,2018-06-16 17:40:00 UTC,auto,hold,716,712,662,KY,Louisville,120,True,False,False,Gas,2018,jun
426859,af074e178c199f0fff346054a7f6c3114bc27bb0,2018-06-15 18:50:00 UTC,auto,hold,713,712,662,KY,Louisville,120,True,False,False,Gas,2018,jun

In [66]:
jun_2018_ave = jun_2018.groupby(['Identifier', 'Month', 'Year','HvacMode','CalendarEvent', 'City']).mean()

# jun_2018_ave

In [67]:
# Export CSV file

jun_2018_ave.to_csv("data/day/KY/jun/jun_2018_ave.csv", header=True, index=True)

### 2019 June Day

In [68]:
# Read in month csv for state
jun_2019 = pd.read_csv("../data_large/KY-day/2019-jun-day-KY.csv")

# jun_2019

In [69]:
# Add year and month

jun_2019["Year"] = "2019"
jun_2019["Month"] = "jun"

In [70]:
# Rename columns to label the aggregates

jun_2019.rename(columns={"Temperature_ctrl":"Temperature_ctrl_ave", 
                         "TemperatureExpectedCool":"TemperatureExpectedCool_ave", 
                         "TemperatureExpectedHeat":"TemperatureExpectedHeat_ave"})

,Identifier,date_time,HvacMode,CalendarEvent,Temperature_ctrl_ave,TemperatureExpectedCool_ave,TemperatureExpectedHeat_ave,ProvinceState,City,Age_of_Home__years_,allowCompWithAux,Has_Electric,Has_a_Heat_Pump,Auxilliary_Heat_Fuel_Type,Year,Month
0,6afa8c18218f1a5d0f4532476084ce250c75141f,2019-06-17 12:30:00 UTC,cool,hold,664,660,660,KY,Shepherdsville,10,False,False,False,Gas,2019,jun
1,f32b0994d982668680970ad64e06e3ab916520e9,2019-06-20 16:55:00 UTC,cool,hold,718,740,740,KY,Shepherdsville,10,True,False,False,Gas,2019,jun
2,6afa8c18218f1a5d0f4532476084ce250c75141f,2019-06-23 12:05:00 UTC,cool,auto,670,670,670,KY,Shepherdsville,10,False,False,False,Gas,2019,jun
3,6afa8c18218f1a5d0f4532476084ce250c75141f,2019-06-28 11:50:00 UTC,cool,auto,681,680,680,KY,Shepherdsville,10,False,False,False,Gas,2019,jun
4,f32b0994d982668680970ad64e06e3ab916520e9,2019-06-29 09:20:00 UTC,cool,hold,700,700,700,KY,Shepherdsville,10,True,False,False,Gas,2019,jun
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
589736,6afa8c18218f1a5d0f4532476084ce250c75141f,2019-06-02 11:45:00 UTC,cool,auto,675,670,670,KY,Shepherdsville,10,False,False,False,Gas,2019,jun
589737,f32b0994d982668680970ad64e06e3ab916520e9,2019-06-16 07:30:00 UTC,cool,auto,741,740,735,KY,Shepherdsville,10,True,False,False,Gas,2019,jun
589738,6afa8c18218f1a5d0f4532476084ce250c75141f,2019-06-23 13:50:00 UTC,cool,auto,675,670,670,KY,Shepherdsville,10,False,False,False,Gas,2019,jun
589739,f32b0994d982668680970ad64e06e3ab916520e9,2019-06-09 17:20:00 UTC,cool,hold,704,700,700,KY,Shepherdsville,10,True,False,False,Gas,2019,jun
589740,6afa8c18218f1a5d0f4532476084ce250c75141f,2019-06-02 17:35:00 UTC,cool,auto,695,690,690,KY,Shepherdsville,10,False,False,False,Gas,2019,jun

In [71]:
jun_2019_ave = jun_2019.groupby(['Identifier', 'Month', 'Year','HvacMode','CalendarEvent', 'City']).mean()

# jun_2019_ave

In [72]:
# Export CSV file

jun_2019_ave.to_csv("data/day/KY/jun/jun_2019_ave.csv", header=True, index=True)

### 2020 June Day

In [73]:
# Read in month csv for state
jun_2020 = pd.read_csv("../data_large/KY-day/2020-jun-day-KY.csv")

# jun_2020

In [74]:
# Add year and month

jun_2020["Year"] = "2020"
jun_2020["Month"] = "jun"

In [75]:
# Rename columns to label the aggregates

jun_2020.rename(columns={"Temperature_ctrl":"Temperature_ctrl_ave", 
                         "TemperatureExpectedCool":"TemperatureExpectedCool_ave", 
                         "TemperatureExpectedHeat":"TemperatureExpectedHeat_ave"})

,Identifier,date_time,HvacMode,CalendarEvent,Temperature_ctrl_ave,TemperatureExpectedCool_ave,TemperatureExpectedHeat_ave,ProvinceState,City,Age_of_Home__years_,allowCompWithAux,Has_Electric,Has_a_Heat_Pump,Auxilliary_Heat_Fuel_Type,Year,Month
0,c2c20f09a15771decb656a0e7fd0be6f529101cd,2020-06-25 11:30:00 UTC,cool,hold,681,690,690,KY,Vine Grove,28,True,False,True,Electric,2020,jun
1,00105867bef9463f0a62d5257d0e91b8c8d19dee,2020-06-17 11:00:00 UTC,cool,hold,697,700,700,KY,Southgate,75,False,False,False,Gas,2020,jun
2,0c63b911c56082695f9c7416781cd37dbcad2262,2020-06-30 14:55:00 UTC,auto,auto,751,760,690,KY,Murray,58,False,False,False,Gas,2020,jun
3,3ddcf8c99249bbefb2b23450d38a8b3f25dc19a7,2020-06-06 11:25:00 UTC,cool,auto,728,730,730,KY,Highlands,100,False,False,False,Gas,2020,jun
4,c2c20f09a15771decb656a0e7fd0be6f529101cd,2020-06-03 11:25:00 UTC,cool,auto,690,690,640,KY,Vine Grove,28,True,False,True,Electric,2020,jun
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
575740,628b89c27b7633e93a2abe430b726e3018266a4a,2020-06-16 16:30:00 UTC,cool,hold,708,740,740,KY,Georgetown,120,False,False,True,Electric,2020,jun
575741,628b89c27b7633e93a2abe430b726e3018266a4a,2020-06-12 14:10:00 UTC,cool,hold,727,730,730,KY,Georgetown,120,False,False,True,Electric,2020,jun
575742,628b89c27b7633e93a2abe430b726e3018266a4a,2020-06-28 16:35:00 UTC,cool,hold,737,740,740,KY,Georgetown,120,False,False,True,Electric,2020,jun
575743,628b89c27b7633e93a2abe430b726e3018266a4a,2020-06-26 17:50:00 UTC,cool,hold,730,730,730,KY,Georgetown,120,False,False,True,Electric,2020,jun
575744,af074e178c199f0fff346054a7f6c3114bc27bb0,2020-06-27 17:45:00 UTC,auto,hold,746,742,662,KY,Louisville,120,True,False,False,Gas,2020,jun

In [76]:
jun_2020_ave = jun_2020.groupby(['Identifier', 'Month', 'Year','HvacMode','CalendarEvent', 'City']).mean()

# jun_2020_ave

In [77]:
# Export CSV file

jun_2020_ave.to_csv("data/day/KY/jun/jun_2020_ave.csv", header=True, index=True)

### 2021 June Day

In [78]:
# Read in month csv for state
jun_2021 = pd.read_csv("../data_large/KY-day/2021-jun-day-KY.csv")

# jun_2021

In [79]:
# Add year and month

jun_2021["Year"] = "2021"
jun_2021["Month"] = "jun"

In [80]:
# Rename columns to label the aggregates

jun_2021.rename(columns={"Temperature_ctrl":"Temperature_ctrl_ave", 
                         "TemperatureExpectedCool":"TemperatureExpectedCool_ave", 
                         "TemperatureExpectedHeat":"TemperatureExpectedHeat_ave"})

,Identifier,date_time,HvacMode,CalendarEvent,Temperature_ctrl_ave,TemperatureExpectedCool_ave,TemperatureExpectedHeat_ave,ProvinceState,City,Age_of_Home__years_,allowCompWithAux,Has_Electric,Has_a_Heat_Pump,Auxilliary_Heat_Fuel_Type,Year,Month
0,56f54fb3fa14bf1c16c79b63de32965c79394dc5,2021-06-19 16:10:00 UTC,cool,hold,690,675,675,KY,Goshen,36,False,False,True,Electric,2021,jun
1,00105867bef9463f0a62d5257d0e91b8c8d19dee,2021-06-05 13:15:00 UTC,cool,hold,704,705,705,KY,Southgate,75,False,False,False,Gas,2021,jun
2,36e5a77bf644b37f395da007bc371ed9bcc4160b,2021-06-06 17:50:00 UTC,cool,hold,719,720,720,KY,Benton,19,False,False,True,Electric,2021,jun
3,d61a5a18aab25a00f0f96411957106752a9b4c2e,2021-06-07 19:05:00 UTC,cool,hold,709,700,700,KY,Salyersville,39,True,False,True,Electric,2021,jun
4,a85176f7816955f77859fb3fbc12843017170f61,2021-06-07 18:15:00 UTC,auto,hold,699,700,650,KY,Newport,110,False,False,False,Gas,2021,jun
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
347500,628b89c27b7633e93a2abe430b726e3018266a4a,2021-06-15 15:40:00 UTC,cool,hold,742,760,760,KY,Georgetown,120,False,False,True,Electric,2021,jun
347501,628b89c27b7633e93a2abe430b726e3018266a4a,2021-06-20 17:45:00 UTC,cool,hold,755,760,760,KY,Georgetown,120,False,False,True,Electric,2021,jun
347502,628b89c27b7633e93a2abe430b726e3018266a4a,2021-06-24 15:05:00 UTC,cool,hold,708,760,760,KY,Georgetown,120,False,False,True,Electric,2021,jun
347503,628b89c27b7633e93a2abe430b726e3018266a4a,2021-06-19 11:30:00 UTC,cool,hold,750,760,760,KY,Georgetown,120,False,False,True,Electric,2021,jun
347504,628b89c27b7633e93a2abe430b726e3018266a4a,2021-06-22 11:55:00 UTC,cool,hold,727,760,760,KY,Georgetown,120,False,False,True,Electric,2021,jun

In [81]:
jun_2021_ave = jun_2021.groupby(['Identifier', 'Month', 'Year','HvacMode','CalendarEvent', 'City']).mean()

# jun_2021_ave

In [82]:
# Export CSV file

jun_2021_ave.to_csv("data/day/KY/jun/jun_2021_ave.csv", header=True, index=True)

---

### Combine month CSV Files 
1. Read in files in folders for each state
2. Export as combined CSV

In [83]:
# Create variable for files in directory
files = [f for f in os.listdir("data/day/KY/jun/") if f.endswith(".csv")]

# files

In [84]:
# https://stackoverflow.com/questions/63886787/how-to-create-a-dataframe-from-multiple-csv-files
# InitiKYize and empty dataframe
KY_jun = pd.DataFrame()

# Iterate through files and contents, then concatenate the data into the dataframe
for file in files:
    df = pd.read_csv("data/day/KY/jun/" + file)
    KY_jun = pd.concat([KY_jun, df])
    
KY_jun

,Identifier,Month,Year,HvacMode,CalendarEvent,City,Temperature_ctrl,TemperatureExpectedCool,TemperatureExpectedHeat,Age_of_Home__years_,allowCompWithAux,Has_Electric,Has_a_Heat_Pump
0,008cfa92481086d7def321eeabb85c0d3eb846de,jun,2017,cool,auto,Campbellsville,700.013423,694.348993,680.000000,5.0,True,False,True
1,008cfa92481086d7def321eeabb85c0d3eb846de,jun,2017,cool,hold,Campbellsville,702.457399,695.493274,695.430493,5.0,True,False,True
2,020ded524bca03fd8503e9676cbd617ae62f12d4,jun,2017,auto,auto,Louisville,708.918919,707.540541,619.806950,15.0,False,False,False
3,020ded524bca03fd8503e9676cbd617ae62f12d4,jun,2017,auto,hold,Louisville,696.185647,704.814353,639.995320,15.0,False,False,False
4,0475b61636d4d1ba679fd87d374f57927081105b,jun,2017,auto,auto,Independence,750.932258,774.785484,661.664516,20.0,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
429,fd49781b1b98414ed0495e079dd5435a549a7a86,jun,2021,heat,hold,Alexandria,703.504950,688.287129,688.287129,5.0,False,False,True
430,fd8aaf4038f451870fc23ab85245f4ca4a83a354,jun,2021,auto,hold,Lexington,662.339726,663.895890,583.106849,18.0,False,False,True
431,fefca5ecf57c50c2f337a1de4577dae3d020f2cd,jun,2021,cool,hold,Lexington,729.707865,720.415730,719.842697,8.0,True,False,True
432,ff1640c73f967b557d8c64dff6f8139a85e71d38,jun,2021,auto,hold,Georgetown,691.604651,686.279070,646.674419,15.0,True,False,True
433,ffbcfc7a85b89b45816e8c216f602c018c63777e,jun,2021,cool,hold,Lexington,723.944444,720.000000,720.000000,5.0,False,False,True

In [85]:
KY_jun.to_csv("Scraper_Output/State_Month_Day/KY/KY_jun.csv", header=True, index=False)

---

## July

### 2017 July Day

In [86]:
# Read in month csv for state
jul_2017 = pd.read_csv("../data_large/KY-day/2017-jul-day-KY.csv")

# jul_2017

In [87]:
# Add year and month

jul_2017["Year"] = "2017"
jul_2017["Month"] = "jul"

In [88]:
# Rename columns to label the aggregates

jul_2017.rename(columns={"Temperature_ctrl":"Temperature_ctrl_ave", 
                         "TemperatureExpectedCool":"TemperatureExpectedCool_ave", 
                         "TemperatureExpectedHeat":"TemperatureExpectedHeat_ave"})

,Identifier,date_time,HvacMode,CalendarEvent,Temperature_ctrl_ave,TemperatureExpectedCool_ave,TemperatureExpectedHeat_ave,ProvinceState,City,Age_of_Home__years_,allowCompWithAux,Has_Electric,Has_a_Heat_Pump,Auxilliary_Heat_Fuel_Type,Year,Month
0,0f739392cb73489df16d6bd5cce782aa26047ea0,2017-07-01 19:10:00 UTC,auto,auto,754,720,600,KY,Hickman,85,False,False,False,Gas,2017,jul
1,0f739392cb73489df16d6bd5cce782aa26047ea0,2017-07-01 19:35:00 UTC,auto,auto,763,720,600,KY,Hickman,85,False,False,False,Gas,2017,jul
2,00105867bef9463f0a62d5257d0e91b8c8d19dee,2017-07-09 19:00:00 UTC,cool,hold,715,700,700,KY,Southgate,75,False,False,False,Gas,2017,jul
3,0f739392cb73489df16d6bd5cce782aa26047ea0,2017-07-08 17:45:00 UTC,auto,auto,767,750,600,KY,Hickman,85,False,False,False,Gas,2017,jul
4,0f739392cb73489df16d6bd5cce782aa26047ea0,2017-07-08 18:55:00 UTC,auto,auto,775,750,600,KY,Hickman,85,False,False,False,Gas,2017,jul
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234023,441f78bdc893c61cc6bf174cf95fea1fe597fc91,2017-07-05 18:00:00 UTC,cool,hold,748,750,750,KY,Louisville,90,False,False,False,Gas,2017,jul
234024,262c461792e30453d14b0e95ebe729512187b0f4,2017-07-02 15:25:00 UTC,cool,hold,726,720,720,KY,Louisville,90,False,False,False,Gas,2017,jul
234025,7eb6c3424f78bab4592372fd0a430b52146e201e,2017-07-18 15:25:00 UTC,cool,hold,734,730,730,KY,Louisville,90,False,False,False,Gas,2017,jul
234026,441f78bdc893c61cc6bf174cf95fea1fe597fc91,2017-07-20 12:45:00 UTC,cool,auto,734,730,740,KY,Louisville,90,False,False,False,Gas,2017,jul
234027,441f78bdc893c61cc6bf174cf95fea1fe597fc91,2017-07-18 19:05:00 UTC,cool,auto,730,730,740,KY,Louisville,90,False,False,False,Gas,2017,jul

In [89]:
jul_2017_ave = jul_2017.groupby(['Identifier', 'Month', 'Year','HvacMode','CalendarEvent', 'City']).mean()

# jul_2017_ave

In [90]:
# Export CSV file

jul_2017_ave.to_csv("data/day/KY/jul/jul_2017_ave.csv", header=True, index=True)

### 2018 July Day

In [91]:
# Read in month csv for state
jul_2018 = pd.read_csv("../data_large/KY-day/2018-jul-day-KY.csv")

# jul_2018

In [92]:
# Add year and month

jul_2018["Year"] = "2018"
jul_2018["Month"] = "jul"

In [93]:
# Rename columns to label the aggregates

jul_2018.rename(columns={"Temperature_ctrl":"Temperature_ctrl_ave", 
                         "TemperatureExpectedCool":"TemperatureExpectedCool_ave", 
                         "TemperatureExpectedHeat":"TemperatureExpectedHeat_ave"})

,Identifier,date_time,HvacMode,CalendarEvent,Temperature_ctrl_ave,TemperatureExpectedCool_ave,TemperatureExpectedHeat_ave,ProvinceState,City,Age_of_Home__years_,allowCompWithAux,Has_Electric,Has_a_Heat_Pump,Auxilliary_Heat_Fuel_Type,Year,Month
0,cbdb5db5ce0fcdae40f28f81305bfbbfa747dc4c,2018-07-29 10:45:00 UTC,cool,hold,699,700,700,KY,Crestview Hills,38,True,False,True,Electric,2018,jul
1,cbdb5db5ce0fcdae40f28f81305bfbbfa747dc4c,2018-07-29 10:50:00 UTC,cool,hold,699,700,700,KY,Crestview Hills,38,True,False,True,Electric,2018,jul
2,cbdb5db5ce0fcdae40f28f81305bfbbfa747dc4c,2018-07-21 12:30:00 UTC,cool,hold,702,700,700,KY,Crestview Hills,38,True,False,True,Electric,2018,jul
3,cbdb5db5ce0fcdae40f28f81305bfbbfa747dc4c,2018-07-12 12:50:00 UTC,cool,auto,710,710,680,KY,Crestview Hills,38,True,False,True,Electric,2018,jul
4,d117ee90b026d4dc02dbe36b7e9d1d250274bb5d,2018-07-09 10:45:00 UTC,cool,auto,727,730,730,KY,Mt. Washington,47,True,False,True,Electric,2018,jul
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
490679,af074e178c199f0fff346054a7f6c3114bc27bb0,2018-07-04 16:10:00 UTC,auto,hold,730,722,672,KY,Louisville,120,True,False,False,Gas,2018,jul
490680,af074e178c199f0fff346054a7f6c3114bc27bb0,2018-07-04 14:25:00 UTC,auto,hold,727,722,672,KY,Louisville,120,True,False,False,Gas,2018,jul
490681,af074e178c199f0fff346054a7f6c3114bc27bb0,2018-07-02 16:50:00 UTC,auto,hold,741,722,672,KY,Louisville,120,True,False,False,Gas,2018,jul
490682,af074e178c199f0fff346054a7f6c3114bc27bb0,2018-07-03 14:40:00 UTC,auto,hold,724,722,672,KY,Louisville,120,True,False,False,Gas,2018,jul
490683,af074e178c199f0fff346054a7f6c3114bc27bb0,2018-07-02 15:40:00 UTC,auto,auto,736,732,682,KY,Louisville,120,True,False,False,Gas,2018,jul

In [94]:
jul_2018_ave = jul_2018.groupby(['Identifier', 'Month', 'Year','HvacMode','CalendarEvent', 'City']).mean()

# jul_2018_ave

In [95]:
# Export CSV file

jul_2018_ave.to_csv("data/day/KY/jul/jul_2018_ave.csv", header=True, index=True)

### 2019 July Day

In [96]:
# Read in month csv for state
jul_2019 = pd.read_csv("../data_large/KY-day/2019-jul-day-KY.csv")

# jul_2019

In [97]:
# Add year and month

jul_2019["Year"] = "2019"
jul_2019["Month"] = "jul"

In [98]:
# Rename columns to label the aggregates

jul_2019.rename(columns={"Temperature_ctrl":"Temperature_ctrl_ave", 
                         "TemperatureExpectedCool":"TemperatureExpectedCool_ave", 
                         "TemperatureExpectedHeat":"TemperatureExpectedHeat_ave"})

,Identifier,date_time,HvacMode,CalendarEvent,Temperature_ctrl_ave,TemperatureExpectedCool_ave,TemperatureExpectedHeat_ave,ProvinceState,City,Age_of_Home__years_,allowCompWithAux,Has_Electric,Has_a_Heat_Pump,Auxilliary_Heat_Fuel_Type,Year,Month
0,c2c20f09a15771decb656a0e7fd0be6f529101cd,2019-07-30 15:00:00 UTC,cool,auto,695,690,690,KY,Vine Grove,28,True,False,True,Electric,2019,jul
1,0f739392cb73489df16d6bd5cce782aa26047ea0,2019-07-20 13:05:00 UTC,cool,auto,710,710,710,KY,Hickman,85,False,False,False,Gas,2019,jul
2,c2c20f09a15771decb656a0e7fd0be6f529101cd,2019-07-16 14:05:00 UTC,cool,auto,691,690,690,KY,Vine Grove,28,True,False,True,Electric,2019,jul
3,c2c20f09a15771decb656a0e7fd0be6f529101cd,2019-07-16 13:25:00 UTC,cool,auto,696,690,690,KY,Vine Grove,28,True,False,True,Electric,2019,jul
4,0f739392cb73489df16d6bd5cce782aa26047ea0,2019-07-13 12:35:00 UTC,cool,auto,731,730,720,KY,Hickman,85,False,False,False,Gas,2019,jul
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
622258,628b89c27b7633e93a2abe430b726e3018266a4a,2019-07-19 16:55:00 UTC,cool,auto,740,740,740,KY,Georgetown,120,False,False,True,Electric,2019,jul
622259,628b89c27b7633e93a2abe430b726e3018266a4a,2019-07-26 09:45:00 UTC,cool,hold,733,740,740,KY,Georgetown,120,False,False,True,Electric,2019,jul
622260,628b89c27b7633e93a2abe430b726e3018266a4a,2019-07-20 14:15:00 UTC,cool,hold,736,740,740,KY,Georgetown,120,False,False,True,Electric,2019,jul
622261,628b89c27b7633e93a2abe430b726e3018266a4a,2019-07-22 16:35:00 UTC,cool,hold,755,750,750,KY,Georgetown,120,False,False,True,Electric,2019,jul
622262,628b89c27b7633e93a2abe430b726e3018266a4a,2019-07-29 12:35:00 UTC,cool,hold,752,750,750,KY,Georgetown,120,False,False,True,Electric,2019,jul

In [99]:
jul_2019_ave = jul_2019.groupby(['Identifier', 'Month', 'Year','HvacMode','CalendarEvent', 'City']).mean()

# jul_2019_ave

In [100]:
# Export CSV file

jul_2019_ave.to_csv("data/day/KY/jul/jul_2019_ave.csv", header=True, index=True)

### 2020 July Day

In [101]:
# Read in month csv for state
jul_2020 = pd.read_csv("../data_large/KY-day/2020-jul-day-KY.csv")

# jul_2020

In [102]:
# Add year and month

jul_2020["Year"] = "2020"
jul_2020["Month"] = "jul"

In [103]:
# Rename columns to label the aggregates

jul_2020.rename(columns={"Temperature_ctrl":"Temperature_ctrl_ave", 
                         "TemperatureExpectedCool":"TemperatureExpectedCool_ave", 
                         "TemperatureExpectedHeat":"TemperatureExpectedHeat_ave"})

,Identifier,date_time,HvacMode,CalendarEvent,Temperature_ctrl_ave,TemperatureExpectedCool_ave,TemperatureExpectedHeat_ave,ProvinceState,City,Age_of_Home__years_,allowCompWithAux,Has_Electric,Has_a_Heat_Pump,Auxilliary_Heat_Fuel_Type,Year,Month
0,a85176f7816955f77859fb3fbc12843017170f61,2020-07-04 19:00:00 UTC,cool,auto,764,800,600,KY,Newport,110,False,False,False,Gas,2020,jul
1,3ddcf8c99249bbefb2b23450d38a8b3f25dc19a7,2020-07-05 10:55:00 UTC,cool,hold,738,760,760,KY,Highlands,100,False,False,False,Gas,2020,jul
2,3ddcf8c99249bbefb2b23450d38a8b3f25dc19a7,2020-07-01 19:00:00 UTC,auto,auto,719,710,620,KY,Highlands,100,False,False,False,Gas,2020,jul
3,d61a5a18aab25a00f0f96411957106752a9b4c2e,2020-07-22 17:40:00 UTC,cool,hold,705,700,700,KY,Salyersville,39,True,False,True,Electric,2020,jul
4,31ed9378d5a4cc5c6883c1f09c95c15cec33373d,2020-07-26 14:05:00 UTC,cool,auto,687,690,690,KY,Mount Washington,39,False,False,True,Electric,2020,jul
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595532,628b89c27b7633e93a2abe430b726e3018266a4a,2020-07-27 10:05:00 UTC,cool,hold,740,740,740,KY,Georgetown,120,False,False,True,Electric,2020,jul
595533,628b89c27b7633e93a2abe430b726e3018266a4a,2020-07-28 11:55:00 UTC,cool,hold,736,740,740,KY,Georgetown,120,False,False,True,Electric,2020,jul
595534,628b89c27b7633e93a2abe430b726e3018266a4a,2020-07-31 17:15:00 UTC,cool,hold,718,720,720,KY,Georgetown,120,False,False,True,Electric,2020,jul
595535,628b89c27b7633e93a2abe430b726e3018266a4a,2020-07-11 10:30:00 UTC,cool,hold,728,730,730,KY,Georgetown,120,False,False,True,Electric,2020,jul
595536,628b89c27b7633e93a2abe430b726e3018266a4a,2020-07-16 15:15:00 UTC,cool,hold,737,740,740,KY,Georgetown,120,False,False,True,Electric,2020,jul

In [104]:
jul_2020_ave = jul_2020.groupby(['Identifier', 'Month', 'Year','HvacMode','CalendarEvent', 'City']).mean()

# jul_2020_ave

In [105]:
# Export CSV file

jul_2020_ave.to_csv("data/day/KY/jul/jul_2020_ave.csv", header=True, index=True)

### 2021 July Day

In [106]:
# Read in month csv for state
jul_2021 = pd.read_csv("../data_large/KY-day/2021-jul-day-KY.csv")

# jul_2021

In [107]:
# Add year and month

jul_2021["Year"] = "2021"
jul_2021["Month"] = "jul"

In [108]:
# Rename columns to label the aggregates

jul_2021.rename(columns={"Temperature_ctrl":"Temperature_ctrl_ave", 
                         "TemperatureExpectedCool":"TemperatureExpectedCool_ave", 
                         "TemperatureExpectedHeat":"TemperatureExpectedHeat_ave"})

,Identifier,date_time,HvacMode,CalendarEvent,Temperature_ctrl_ave,TemperatureExpectedCool_ave,TemperatureExpectedHeat_ave,ProvinceState,City,Age_of_Home__years_,allowCompWithAux,Has_Electric,Has_a_Heat_Pump,Auxilliary_Heat_Fuel_Type,Year,Month
0,3ddcf8c99249bbefb2b23450d38a8b3f25dc19a7,2021-07-01 16:05:00 UTC,cool,hold,705,710,710,KY,Highlands,100,False,False,False,Gas,2021,jul
1,a85176f7816955f77859fb3fbc12843017170f61,2021-07-29 17:45:00 UTC,cool,hold,705,680,680,KY,Newport,110,False,False,False,Gas,2021,jul
2,3ddcf8c99249bbefb2b23450d38a8b3f25dc19a7,2021-07-13 17:40:00 UTC,cool,hold,749,720,720,KY,Highlands,100,False,False,False,Gas,2021,jul
3,3ddcf8c99249bbefb2b23450d38a8b3f25dc19a7,2021-07-14 13:00:00 UTC,cool,hold,718,720,720,KY,Highlands,100,False,False,False,Gas,2021,jul
4,d117ee90b026d4dc02dbe36b7e9d1d250274bb5d,2021-07-21 16:10:00 UTC,cool,hold,746,750,750,KY,Mt. Washington,47,True,False,True,Electric,2021,jul
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
318631,628b89c27b7633e93a2abe430b726e3018266a4a,2021-07-13 19:00:00 UTC,cool,hold,716,720,720,KY,Georgetown,120,False,False,True,Electric,2021,jul
318632,628b89c27b7633e93a2abe430b726e3018266a4a,2021-07-01 16:10:00 UTC,cool,hold,742,770,770,KY,Georgetown,120,False,False,True,Electric,2021,jul
318633,628b89c27b7633e93a2abe430b726e3018266a4a,2021-07-13 17:30:00 UTC,cool,hold,728,720,720,KY,Georgetown,120,False,False,True,Electric,2021,jul
318634,628b89c27b7633e93a2abe430b726e3018266a4a,2021-07-04 17:20:00 UTC,cool,hold,736,770,770,KY,Georgetown,120,False,False,True,Electric,2021,jul
318635,628b89c27b7633e93a2abe430b726e3018266a4a,2021-07-02 12:45:00 UTC,cool,hold,732,770,770,KY,Georgetown,120,False,False,True,Electric,2021,jul

In [109]:
jul_2021_ave = jul_2021.groupby(['Identifier', 'Month', 'Year','HvacMode','CalendarEvent', 'City']).mean()

# jul_2021_ave

In [110]:
# Export CSV file

jul_2021_ave.to_csv("data/day/KY/jul/jul_2021_ave.csv", header=True, index=True)

---

### Combine month CSV Files 
1. Read in files in folders for each state
2. Export as combined CSV

In [111]:
# Create variable for files in directory
files = [f for f in os.listdir("data/day/KY/jul/") if f.endswith(".csv")]

# files

In [112]:
# https://stackoverflow.com/questions/63886787/how-to-create-a-dataframe-from-multiple-csv-files
# InitiKYize and empty dataframe
KY_jul = pd.DataFrame()

# Iterate through files and contents, then concatenate the data into the dataframe
for file in files:
    df = pd.read_csv("data/day/KY/jul/" + file)
    KY_jul = pd.concat([KY_jul, df])
    
KY_jul

,Identifier,Month,Year,HvacMode,CalendarEvent,City,Temperature_ctrl,TemperatureExpectedCool,TemperatureExpectedHeat,Age_of_Home__years_,allowCompWithAux,Has_Electric,Has_a_Heat_Pump
0,00105867bef9463f0a62d5257d0e91b8c8d19dee,jul,2017,cool,hold,Southgate,715.631579,700.000000,700.000000,75.0,False,False,False
1,008cfa92481086d7def321eeabb85c0d3eb846de,jul,2017,cool,auto,Campbellsville,706.532468,700.058442,680.000000,5.0,True,False,True
2,008cfa92481086d7def321eeabb85c0d3eb846de,jul,2017,cool,hold,Campbellsville,704.132353,695.573529,695.573529,5.0,True,False,True
3,020ded524bca03fd8503e9676cbd617ae62f12d4,jul,2017,auto,hold,Louisville,711.053571,711.455357,600.000000,15.0,False,False,False
4,0475b61636d4d1ba679fd87d374f57927081105b,jul,2017,auto,auto,Independence,763.537634,780.000000,660.000000,20.0,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
384,fd8aaf4038f451870fc23ab85245f4ca4a83a354,jul,2021,auto,hold,Lexington,665.723077,665.138462,587.000000,18.0,False,False,True
385,fd8aaf4038f451870fc23ab85245f4ca4a83a354,jul,2021,cool,hold,Lexington,666.745665,667.560694,666.693642,18.0,False,False,True
386,fefca5ecf57c50c2f337a1de4577dae3d020f2cd,jul,2021,cool,hold,Lexington,734.782609,726.000000,726.000000,8.0,True,False,True
387,ff1640c73f967b557d8c64dff6f8139a85e71d38,jul,2021,auto,hold,Georgetown,724.770115,724.793103,657.011494,15.0,True,False,True
388,ffbcfc7a85b89b45816e8c216f602c018c63777e,jul,2021,cool,hold,Lexington,722.690476,720.634921,720.634921,5.0,False,False,True

In [113]:
KY_jul.to_csv("Scraper_Output/State_Month_Day/KY/KY_jul.csv", header=True, index=False)

---

## August

### 2017 August Day

In [114]:
# Read in month csv for state
aug_2017 = pd.read_csv("../data_large/KY-day/2017-aug-day-KY.csv")

# aug_2017

In [115]:
# Add year and month

aug_2017["Year"] = "2017"
aug_2017["Month"] = "aug"

In [116]:
# Rename columns to label the aggregates

aug_2017.rename(columns={"Temperature_ctrl":"Temperature_ctrl_ave", 
                         "TemperatureExpectedCool":"TemperatureExpectedCool_ave", 
                         "TemperatureExpectedHeat":"TemperatureExpectedHeat_ave"})

,Identifier,date_time,HvacMode,CalendarEvent,Temperature_ctrl_ave,TemperatureExpectedCool_ave,TemperatureExpectedHeat_ave,ProvinceState,City,Age_of_Home__years_,allowCompWithAux,Has_Electric,Has_a_Heat_Pump,Auxilliary_Heat_Fuel_Type,Year,Month
0,0f739392cb73489df16d6bd5cce782aa26047ea0,2017-08-20 19:15:00 UTC,auto,auto,759,710,600,KY,Hickman,85,False,False,False,Gas,2017,aug
1,00105867bef9463f0a62d5257d0e91b8c8d19dee,2017-08-26 18:40:00 UTC,cool,hold,727,700,700,KY,Southgate,75,False,False,False,Gas,2017,aug
2,00105867bef9463f0a62d5257d0e91b8c8d19dee,2017-08-26 19:20:00 UTC,cool,hold,723,700,700,KY,Southgate,75,False,False,False,Gas,2017,aug
3,00105867bef9463f0a62d5257d0e91b8c8d19dee,2017-08-26 17:40:00 UTC,cool,hold,744,700,700,KY,Southgate,75,False,False,False,Gas,2017,aug
4,0f739392cb73489df16d6bd5cce782aa26047ea0,2017-08-20 19:20:00 UTC,auto,auto,760,710,600,KY,Hickman,85,False,False,False,Gas,2017,aug
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
240547,df93077f04f2403ad7e0a12bce9f526332cc3cc1,2017-08-28 17:10:00 UTC,cool,auto,722,720,730,KY,Louisville,90,False,False,False,Gas,2017,aug
240548,7eb6c3424f78bab4592372fd0a430b52146e201e,2017-08-24 11:50:00 UTC,cool,hold,725,730,730,KY,Louisville,90,False,False,False,Gas,2017,aug
240549,7eb6c3424f78bab4592372fd0a430b52146e201e,2017-08-09 18:00:00 UTC,cool,hold,735,730,730,KY,Louisville,90,False,False,False,Gas,2017,aug
240550,441f78bdc893c61cc6bf174cf95fea1fe597fc91,2017-08-18 10:30:00 UTC,cool,hold,732,730,730,KY,Louisville,90,False,False,False,Gas,2017,aug
240551,262c461792e30453d14b0e95ebe729512187b0f4,2017-08-29 11:55:00 UTC,cool,hold,731,740,740,KY,Louisville,90,False,False,False,Gas,2017,aug

In [117]:
aug_2017_ave = aug_2017.groupby(['Identifier', 'Month', 'Year','HvacMode','CalendarEvent', 'City']).mean()

# aug_2017_ave

In [118]:
# Export CSV file

aug_2017_ave.to_csv("data/day/KY/aug/aug_2017_ave.csv", header=True, index=True)

### 2018 August Day

In [119]:
# Read in month csv for state
aug_2018 = pd.read_csv("../data_large/KY-day/2018-aug-day-KY.csv")

# aug_2018

In [120]:
# Add year and month

aug_2018["Year"] = "2018"
aug_2018["Month"] = "aug"

In [121]:
# Rename columns to label the aggregates

aug_2018.rename(columns={"Temperature_ctrl":"Temperature_ctrl_ave", 
                         "TemperatureExpectedCool":"TemperatureExpectedCool_ave", 
                         "TemperatureExpectedHeat":"TemperatureExpectedHeat_ave"})

,Identifier,date_time,HvacMode,CalendarEvent,Temperature_ctrl_ave,TemperatureExpectedCool_ave,TemperatureExpectedHeat_ave,ProvinceState,City,Age_of_Home__years_,allowCompWithAux,Has_Electric,Has_a_Heat_Pump,Auxilliary_Heat_Fuel_Type,Year,Month
0,cbdb5db5ce0fcdae40f28f81305bfbbfa747dc4c,2018-08-18 19:15:00 UTC,cool,hold,701,700,700,KY,Crestview Hills,38,True,False,True,Electric,2018,aug
1,c2c20f09a15771decb656a0e7fd0be6f529101cd,2018-08-20 12:05:00 UTC,auto,hold,710,709,650,KY,Vine Grove,28,True,False,True,Electric,2018,aug
2,c2c20f09a15771decb656a0e7fd0be6f529101cd,2018-08-28 11:30:00 UTC,auto,hold,699,700,650,KY,Vine Grove,28,True,False,True,Electric,2018,aug
3,a85176f7816955f77859fb3fbc12843017170f61,2018-08-12 14:55:00 UTC,auto,hold,702,700,640,KY,Newport,110,False,False,False,Gas,2018,aug
4,cbdb5db5ce0fcdae40f28f81305bfbbfa747dc4c,2018-08-08 18:50:00 UTC,cool,hold,783,780,780,KY,Crestview Hills,38,True,False,True,Electric,2018,aug
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
461153,af074e178c199f0fff346054a7f6c3114bc27bb0,2018-08-08 16:45:00 UTC,auto,hold,747,742,672,KY,Louisville,120,True,False,False,Gas,2018,aug
461154,af074e178c199f0fff346054a7f6c3114bc27bb0,2018-08-08 10:55:00 UTC,auto,hold,744,742,672,KY,Louisville,120,True,False,False,Gas,2018,aug
461155,af074e178c199f0fff346054a7f6c3114bc27bb0,2018-08-08 19:10:00 UTC,auto,hold,743,742,672,KY,Louisville,120,True,False,False,Gas,2018,aug
461156,af074e178c199f0fff346054a7f6c3114bc27bb0,2018-08-08 17:25:00 UTC,auto,hold,742,742,672,KY,Louisville,120,True,False,False,Gas,2018,aug
461157,af074e178c199f0fff346054a7f6c3114bc27bb0,2018-08-07 18:35:00 UTC,auto,hold,744,742,672,KY,Louisville,120,True,False,False,Gas,2018,aug

In [122]:
aug_2018_ave = aug_2018.groupby(['Identifier', 'Month', 'Year','HvacMode','CalendarEvent', 'City']).mean()

# aug_2018_ave

In [123]:
# Export CSV file

aug_2018_ave.to_csv("data/day/KY/aug/aug_2018_ave.csv", header=True, index=True)

### 2019 August Day

In [124]:
# Read in month csv for state
aug_2019 = pd.read_csv("../data_large/KY-day/2019-aug-day-KY.csv")

# aug_2019

In [125]:
# Add year and month

aug_2019["Year"] = "2019"
aug_2019["Month"] = "aug"

In [126]:
# Rename columns to label the aggregates

aug_2019.rename(columns={"Temperature_ctrl":"Temperature_ctrl_ave", 
                         "TemperatureExpectedCool":"TemperatureExpectedCool_ave", 
                         "TemperatureExpectedHeat":"TemperatureExpectedHeat_ave"})

,Identifier,date_time,HvacMode,CalendarEvent,Temperature_ctrl_ave,TemperatureExpectedCool_ave,TemperatureExpectedHeat_ave,ProvinceState,City,Age_of_Home__years_,allowCompWithAux,Has_Electric,Has_a_Heat_Pump,Auxilliary_Heat_Fuel_Type,Year,Month
0,3ddcf8c99249bbefb2b23450d38a8b3f25dc19a7,2019-08-03 17:15:00 UTC,cool,auto,735,730,730,KY,Highlands,100,False,False,False,Gas,2019,aug
1,c2c20f09a15771decb656a0e7fd0be6f529101cd,2019-08-07 16:05:00 UTC,cool,auto,705,700,700,KY,Vine Grove,28,True,False,True,Electric,2019,aug
2,c2c20f09a15771decb656a0e7fd0be6f529101cd,2019-08-09 16:10:00 UTC,cool,auto,702,700,700,KY,Vine Grove,28,True,False,True,Electric,2019,aug
3,4f4ffa6020a9cb61a4b227fc6a0768e8fa5e8d22,2019-08-18 18:45:00 UTC,cool,auto,733,730,730,KY,Carrollton,19,False,False,False,Gas,2019,aug
4,c2c20f09a15771decb656a0e7fd0be6f529101cd,2019-08-30 10:55:00 UTC,cool,hold,694,700,700,KY,Vine Grove,28,True,False,True,Electric,2019,aug
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
598819,628b89c27b7633e93a2abe430b726e3018266a4a,2019-08-21 12:50:00 UTC,cool,hold,749,750,750,KY,Georgetown,120,False,False,True,Electric,2019,aug
598820,628b89c27b7633e93a2abe430b726e3018266a4a,2019-08-12 09:45:00 UTC,cool,hold,747,750,750,KY,Georgetown,120,False,False,True,Electric,2019,aug
598821,628b89c27b7633e93a2abe430b726e3018266a4a,2019-08-09 19:15:00 UTC,cool,hold,741,740,740,KY,Georgetown,120,False,False,True,Electric,2019,aug
598822,628b89c27b7633e93a2abe430b726e3018266a4a,2019-08-10 11:55:00 UTC,cool,hold,744,750,750,KY,Georgetown,120,False,False,True,Electric,2019,aug
598823,af074e178c199f0fff346054a7f6c3114bc27bb0,2019-08-27 13:45:00 UTC,auto,hold,733,732,682,KY,Louisville,120,True,False,False,Gas,2019,aug

In [127]:
aug_2019_ave = aug_2019.groupby(['Identifier', 'Month', 'Year','HvacMode','CalendarEvent', 'City']).mean()

# aug_2019_ave

In [128]:
# Export CSV file

aug_2019_ave.to_csv("data/day/KY/aug/aug_2019_ave.csv", header=True, index=True)

### 2020 August Day

In [129]:
# Read in month csv for state
aug_2020 = pd.read_csv("../data_large/KY-day/2020-aug-day-KY.csv")

# aug_2020

In [130]:
# Add year and month

aug_2020["Year"] = "2020"
aug_2020["Month"] = "aug"

In [131]:
# Rename columns to label the aggregates

aug_2020.rename(columns={"Temperature_ctrl":"Temperature_ctrl_ave", 
                         "TemperatureExpectedCool":"TemperatureExpectedCool_ave", 
                         "TemperatureExpectedHeat":"TemperatureExpectedHeat_ave"})

,Identifier,date_time,HvacMode,CalendarEvent,Temperature_ctrl_ave,TemperatureExpectedCool_ave,TemperatureExpectedHeat_ave,ProvinceState,City,Age_of_Home__years_,allowCompWithAux,Has_Electric,Has_a_Heat_Pump,Auxilliary_Heat_Fuel_Type,Year,Month
0,c2c20f09a15771decb656a0e7fd0be6f529101cd,2020-08-05 12:15:00 UTC,cool,hold,689,690,690,KY,Vine Grove,28,True,False,True,Electric,2020,aug
1,31ed9378d5a4cc5c6883c1f09c95c15cec33373d,2020-08-28 15:20:00 UTC,cool,auto,702,710,710,KY,Mount Washington,39,False,False,True,Electric,2020,aug
2,c2c20f09a15771decb656a0e7fd0be6f529101cd,2020-08-17 15:35:00 UTC,cool,auto,679,680,640,KY,Vine Grove,28,True,False,True,Electric,2020,aug
3,a85176f7816955f77859fb3fbc12843017170f61,2020-08-05 13:00:00 UTC,cool,auto,722,740,680,KY,Newport,110,False,False,False,Gas,2020,aug
4,6c752ab573d305a9436acfd7f1d2d90027644b4f,2020-08-26 11:50:00 UTC,cool,hold,696,690,690,KY,LOUISVILLE,95,False,False,True,Electric,2020,aug
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
576438,628b89c27b7633e93a2abe430b726e3018266a4a,2020-08-23 11:35:00 UTC,cool,auto,721,740,740,KY,Georgetown,120,False,False,True,Electric,2020,aug
576439,628b89c27b7633e93a2abe430b726e3018266a4a,2020-08-29 18:00:00 UTC,cool,hold,724,720,720,KY,Georgetown,120,False,False,True,Electric,2020,aug
576440,628b89c27b7633e93a2abe430b726e3018266a4a,2020-08-03 19:15:00 UTC,cool,hold,727,730,730,KY,Georgetown,120,False,False,True,Electric,2020,aug
576441,628b89c27b7633e93a2abe430b726e3018266a4a,2020-08-21 10:45:00 UTC,cool,auto,720,720,720,KY,Georgetown,120,False,False,True,Electric,2020,aug
576442,628b89c27b7633e93a2abe430b726e3018266a4a,2020-08-20 16:40:00 UTC,cool,hold,719,730,730,KY,Georgetown,120,False,False,True,Electric,2020,aug

In [132]:
aug_2020_ave = aug_2020.groupby(['Identifier', 'Month', 'Year','HvacMode','CalendarEvent', 'City']).mean()

# aug_2020_ave

In [133]:
# Export CSV file

aug_2020_ave.to_csv("data/day/KY/aug/aug_2020_ave.csv", header=True, index=True)

### 2021 August Day

In [134]:
# # Read in month csv for state
# aug_2021 = pd.read_csv("../data_large/KY-day/2021-aug-day-KY.csv")

# # aug_2021

In [135]:
# # Add year and month

# aug_2021["Year"] = "2021"
# aug_2021["Month"] = "aug"

In [136]:
# # Rename columns to label the aggregates

# aug_2021.rename(columns={"Temperature_ctrl":"Temperature_ctrl_ave", 
#                          "TemperatureExpectedCool":"TemperatureExpectedCool_ave", 
#                          "TemperatureExpectedHeat":"TemperatureExpectedHeat_ave"})

In [137]:
# aug_2021_ave = aug_2021.groupby(['Identifier', 'Month', 'Year','HvacMode','CalendarEvent', 'City']).mean()

# # aug_2021_ave

In [138]:
# # Export CSV file

# aug_2021_ave.to_csv("data/day/KY/aug/aug_2021_ave.csv", header=True, index=True)

---

### Combine month CSV Files 
1. Read in files in folders for each state
2. Export as combined CSV

In [139]:
# Create variable for files in directory
files = [f for f in os.listdir("data/day/KY/aug/") if f.endswith(".csv")]

# files

In [140]:
# https://stackoverflow.com/questions/63886787/how-to-create-a-dataframe-from-multiple-csv-files
# InitiKYize and empty dataframe
KY_aug = pd.DataFrame()

# Iterate through files and contents, then concatenate the data into the dataframe
for file in files:
    df = pd.read_csv("data/day/KY/aug/" + file)
    KY_aug = pd.concat([KY_aug, df])
    
KY_aug

,Identifier,Month,Year,HvacMode,CalendarEvent,City,Temperature_ctrl,TemperatureExpectedCool,TemperatureExpectedHeat,Age_of_Home__years_,allowCompWithAux,Has_Electric,Has_a_Heat_Pump
0,00105867bef9463f0a62d5257d0e91b8c8d19dee,aug,2017,cool,hold,Southgate,728.285714,700.000000,700.000000,75.0,False,False,False
1,008cfa92481086d7def321eeabb85c0d3eb846de,aug,2017,cool,auto,Campbellsville,702.335294,699.223529,680.000000,5.0,True,False,True
2,008cfa92481086d7def321eeabb85c0d3eb846de,aug,2017,cool,hold,Campbellsville,706.809160,700.091603,699.908397,5.0,True,False,True
3,020ded524bca03fd8503e9676cbd617ae62f12d4,aug,2017,auto,auto,Louisville,739.105263,739.684211,600.000000,15.0,False,False,False
4,020ded524bca03fd8503e9676cbd617ae62f12d4,aug,2017,auto,hold,Louisville,719.580153,722.005089,600.000000,15.0,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
717,fd49781b1b98414ed0495e079dd5435a549a7a86,aug,2020,cool,hold,Alexandria,703.346320,697.038961,697.038961,5.0,False,False,True
718,fd8aaf4038f451870fc23ab85245f4ca4a83a354,aug,2020,cool,auto,Lexington,685.321429,685.151786,600.562500,18.0,False,False,True
719,fd8aaf4038f451870fc23ab85245f4ca4a83a354,aug,2020,cool,hold,Lexington,678.763158,682.868421,680.500000,18.0,False,False,True
720,ff1640c73f967b557d8c64dff6f8139a85e71d38,aug,2020,auto,hold,Georgetown,728.826531,736.326531,656.020408,15.0,True,False,True
721,ffbcfc7a85b89b45816e8c216f602c018c63777e,aug,2020,cool,hold,Lexington,758.000000,720.000000,720.000000,5.0,False,False,True

In [141]:
KY_aug.to_csv("Scraper_Output/State_Month_Day/KY/KY_aug.csv", header=True, index=False)

---

## September

---

## October

---

## November

---

## December

### 2017 December Day

In [142]:
# Read in month csv for state
dec_2017 = pd.read_csv("../data_large/KY-day/2017-dec-day-KY.csv")

# dec_2017

In [143]:
# Add year and month

dec_2017["Year"] = "2017"
dec_2017["Month"] = "dec"

In [144]:
# Rename columns to label the aggregates

dec_2017.rename(columns={"Temperature_ctrl":"Temperature_ctrl_ave", 
                         "TemperatureExpectedCool":"TemperatureExpectedCool_ave", 
                         "TemperatureExpectedHeat":"TemperatureExpectedHeat_ave"})

,Identifier,date_time,HvacMode,CalendarEvent,Temperature_ctrl_ave,TemperatureExpectedCool_ave,TemperatureExpectedHeat_ave,ProvinceState,City,Age_of_Home__years_,allowCompWithAux,Has_Electric,Has_a_Heat_Pump,Auxilliary_Heat_Fuel_Type,Year,Month
0,00105867bef9463f0a62d5257d0e91b8c8d19dee,2017-12-30 19:25:00 UTC,heat,auto,624,650,630,KY,Southgate,75,False,False,False,Gas,2017,dec
1,d117ee90b026d4dc02dbe36b7e9d1d250274bb5d,2017-12-09 19:05:00 UTC,heat,auto,721,710,710,KY,Mt. Washington,47,True,False,True,Electric,2017,dec
2,d117ee90b026d4dc02dbe36b7e9d1d250274bb5d,2017-12-20 11:35:00 UTC,heat,auto,698,690,690,KY,Mt. Washington,47,True,False,True,Electric,2017,dec
3,d117ee90b026d4dc02dbe36b7e9d1d250274bb5d,2017-12-17 17:25:00 UTC,heat,hold,710,700,700,KY,Mt. Washington,47,True,False,True,Electric,2017,dec
4,d117ee90b026d4dc02dbe36b7e9d1d250274bb5d,2017-12-04 16:40:00 UTC,auto,auto,699,745,695,KY,Mt. Washington,47,True,False,True,Electric,2017,dec
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299943,1284a01c8a2c0320c4d7a69983a5e2e33658f3ce,2017-12-05 18:35:00 UTC,heat,hold,683,680,680,KY,Georgetown,120,True,False,True,Electric,2017,dec
299944,1284a01c8a2c0320c4d7a69983a5e2e33658f3ce,2017-12-08 10:40:00 UTC,heat,auto,686,680,680,KY,Georgetown,120,True,False,True,Electric,2017,dec
299945,1284a01c8a2c0320c4d7a69983a5e2e33658f3ce,2017-12-21 15:30:00 UTC,heat,hold,678,680,680,KY,Georgetown,120,True,False,True,Electric,2017,dec
299946,1284a01c8a2c0320c4d7a69983a5e2e33658f3ce,2017-12-13 19:05:00 UTC,heat,hold,672,680,680,KY,Georgetown,120,True,False,True,Electric,2017,dec
299947,628b89c27b7633e93a2abe430b726e3018266a4a,2017-12-18 19:40:00 UTC,heat,hold,664,670,670,KY,Georgetown,120,False,False,True,Electric,2017,dec

In [145]:
dec_2017_ave = dec_2017.groupby(['Identifier', 'Month', 'Year','HvacMode','CalendarEvent', 'City']).mean()

# dec_2017_ave

In [146]:
# Export CSV file

dec_2017_ave.to_csv("data/day/KY/dec/dec_2017_ave.csv", header=True, index=True)

### 2018 December Day

In [147]:
# Read in month csv for state
dec_2018 = pd.read_csv("../data_large/KY-day/2018-dec-day-KY.csv")

# dec_2018

In [148]:
# Add year and month

dec_2018["Year"] = "2018"
dec_2018["Month"] = "dec"

In [149]:
# Rename columns to label the aggregates

dec_2018.rename(columns={"Temperature_ctrl":"Temperature_ctrl_ave", 
                         "TemperatureExpectedCool":"TemperatureExpectedCool_ave", 
                         "TemperatureExpectedHeat":"TemperatureExpectedHeat_ave"})

,Identifier,date_time,HvacMode,CalendarEvent,Temperature_ctrl_ave,TemperatureExpectedCool_ave,TemperatureExpectedHeat_ave,ProvinceState,City,Age_of_Home__years_,allowCompWithAux,Has_Electric,Has_a_Heat_Pump,Auxilliary_Heat_Fuel_Type,Year,Month
0,d117ee90b026d4dc02dbe36b7e9d1d250274bb5d,2018-12-01 16:30:00 UTC,heat,auto,675,780,620,KY,Mt. Washington,47,True,False,True,Electric,2018,dec
1,c2c20f09a15771decb656a0e7fd0be6f529101cd,2018-12-08 16:00:00 UTC,heat,hold,691,700,700,KY,Vine Grove,28,True,False,True,Electric,2018,dec
2,0c63b911c56082695f9c7416781cd37dbcad2262,2018-12-10 13:40:00 UTC,auto,auto,690,780,690,KY,Murray,58,False,False,False,Gas,2018,dec
3,a85176f7816955f77859fb3fbc12843017170f61,2018-12-29 14:50:00 UTC,auto,hold,691,770,690,KY,Newport,110,False,False,False,Gas,2018,dec
4,c2c20f09a15771decb656a0e7fd0be6f529101cd,2018-12-09 16:55:00 UTC,heat,hold,693,700,700,KY,Vine Grove,28,True,False,True,Electric,2018,dec
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
461274,1284a01c8a2c0320c4d7a69983a5e2e33658f3ce,2018-12-16 12:20:00 UTC,heat,auto,688,700,700,KY,Georgetown,120,True,False,True,Electric,2018,dec
461275,1284a01c8a2c0320c4d7a69983a5e2e33658f3ce,2018-12-31 18:00:00 UTC,heat,hold,687,680,680,KY,Georgetown,120,True,False,True,Electric,2018,dec
461276,628b89c27b7633e93a2abe430b726e3018266a4a,2018-12-03 17:10:00 UTC,heat,auto,675,680,680,KY,Georgetown,120,False,False,True,Electric,2018,dec
461277,628b89c27b7633e93a2abe430b726e3018266a4a,2018-12-24 15:10:00 UTC,heat,hold,691,700,700,KY,Georgetown,120,False,False,True,Electric,2018,dec
461278,af074e178c199f0fff346054a7f6c3114bc27bb0,2018-12-04 11:50:00 UTC,auto,hold,693,742,692,KY,Louisville,120,True,False,False,Gas,2018,dec

In [150]:
dec_2018_ave = dec_2018.groupby(['Identifier', 'Month', 'Year','HvacMode','CalendarEvent', 'City']).mean()

# dec_2018_ave

In [151]:
# Export CSV file

dec_2018_ave.to_csv("data/day/KY/dec/dec_2018_ave.csv", header=True, index=True)

### 2019 December Day

In [152]:
# Read in month csv for state
dec_2019 = pd.read_csv("../data_large/KY-day/2019-dec-day-KY.csv")

# dec_2019

In [153]:
# Add year and month

dec_2019["Year"] = "2019"
dec_2019["Month"] = "dec"

In [154]:
# Rename columns to label the aggregates

dec_2019.rename(columns={"Temperature_ctrl":"Temperature_ctrl_ave", 
                         "TemperatureExpectedCool":"TemperatureExpectedCool_ave", 
                         "TemperatureExpectedHeat":"TemperatureExpectedHeat_ave"})

,Identifier,date_time,HvacMode,CalendarEvent,Temperature_ctrl_ave,TemperatureExpectedCool_ave,TemperatureExpectedHeat_ave,ProvinceState,City,Age_of_Home__years_,allowCompWithAux,Has_Electric,Has_a_Heat_Pump,Auxilliary_Heat_Fuel_Type,Year,Month
0,8c1eae3eccaf4af9d9dcaa4e25ddb883d6339700,2019-12-21 19:05:00 UTC,heat,hold,694,670,670,KY,Versailles,39,True,False,True,Electric,2019,dec
1,a85176f7816955f77859fb3fbc12843017170f61,2019-12-01 15:30:00 UTC,heat,auto,692,700,700,KY,Newport,110,False,False,False,Gas,2019,dec
2,3ddcf8c99249bbefb2b23450d38a8b3f25dc19a7,2019-12-14 13:45:00 UTC,heat,hold,627,650,629,KY,Highlands,100,False,False,False,Gas,2019,dec
3,3ddcf8c99249bbefb2b23450d38a8b3f25dc19a7,2019-12-12 12:10:00 UTC,heat,hold,643,650,649,KY,Highlands,100,False,False,False,Gas,2019,dec
4,31ed9378d5a4cc5c6883c1f09c95c15cec33373d,2019-12-19 14:00:00 UTC,heat,hold,679,700,700,KY,Mount Washington,39,False,False,True,Electric,2019,dec
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
543801,628b89c27b7633e93a2abe430b726e3018266a4a,2019-12-31 16:20:00 UTC,heat,hold,697,700,700,KY,Georgetown,120,False,False,True,Electric,2019,dec
543802,628b89c27b7633e93a2abe430b726e3018266a4a,2019-12-14 15:30:00 UTC,heat,hold,693,700,700,KY,Georgetown,120,False,False,True,Electric,2019,dec
543803,628b89c27b7633e93a2abe430b726e3018266a4a,2019-12-20 16:15:00 UTC,heat,hold,675,680,680,KY,Georgetown,120,False,False,True,Electric,2019,dec
543804,628b89c27b7633e93a2abe430b726e3018266a4a,2019-12-16 15:05:00 UTC,heat,hold,679,680,680,KY,Georgetown,120,False,False,True,Electric,2019,dec
543805,628b89c27b7633e93a2abe430b726e3018266a4a,2019-12-26 11:25:00 UTC,heat,hold,679,680,680,KY,Georgetown,120,False,False,True,Electric,2019,dec

In [155]:
dec_2019_ave = dec_2019.groupby(['Identifier', 'Month', 'Year','HvacMode','CalendarEvent', 'City']).mean()

# dec_2019_ave

In [156]:
# Export CSV file

dec_2019_ave.to_csv("data/day/KY/dec/dec_2019_ave.csv", header=True, index=True)

### 2020 December Day

In [157]:
# Read in month csv for state
dec_2020 = pd.read_csv("../data_large/KY-day/2020-dec-day-KY.csv")

# dec_2020

In [158]:
# Add year and month

dec_2020["Year"] = "2020"
dec_2020["Month"] = "dec"

In [159]:
# Rename columns to label the aggregates

dec_2020.rename(columns={"Temperature_ctrl":"Temperature_ctrl_ave", 
                         "TemperatureExpectedCool":"TemperatureExpectedCool_ave", 
                         "TemperatureExpectedHeat":"TemperatureExpectedHeat_ave"})

,Identifier,date_time,HvacMode,CalendarEvent,Temperature_ctrl_ave,TemperatureExpectedCool_ave,TemperatureExpectedHeat_ave,ProvinceState,City,Age_of_Home__years_,allowCompWithAux,Has_Electric,Has_a_Heat_Pump,Auxilliary_Heat_Fuel_Type,Year,Month
0,31ed9378d5a4cc5c6883c1f09c95c15cec33373d,2020-12-20 13:20:00 UTC,heat,hold,672,695,695,KY,Mount Washington,39,False,False,True,Electric,2020,dec
1,c2c20f09a15771decb656a0e7fd0be6f529101cd,2020-12-02 11:35:00 UTC,heat,auto,682,750,690,KY,Vine Grove,28,True,False,True,Electric,2020,dec
2,56f54fb3fa14bf1c16c79b63de32965c79394dc5,2020-12-06 15:30:00 UTC,heat,hold,694,697,697,KY,Goshen,36,False,False,True,Electric,2020,dec
3,31ed9378d5a4cc5c6883c1f09c95c15cec33373d,2020-12-14 15:20:00 UTC,heat,auto,687,700,700,KY,Mount Washington,39,False,False,True,Electric,2020,dec
4,3ddcf8c99249bbefb2b23450d38a8b3f25dc19a7,2020-12-02 17:45:00 UTC,heat,hold,691,690,690,KY,Highlands,100,False,False,False,Gas,2020,dec
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
465169,628b89c27b7633e93a2abe430b726e3018266a4a,2020-12-25 19:45:00 UTC,heat,hold,712,710,710,KY,Georgetown,120,False,False,True,Electric,2020,dec
465170,628b89c27b7633e93a2abe430b726e3018266a4a,2020-12-06 18:55:00 UTC,heat,hold,690,700,700,KY,Georgetown,120,False,False,True,Electric,2020,dec
465171,628b89c27b7633e93a2abe430b726e3018266a4a,2020-12-20 14:45:00 UTC,heat,hold,705,710,710,KY,Georgetown,120,False,False,True,Electric,2020,dec
465172,628b89c27b7633e93a2abe430b726e3018266a4a,2020-12-13 12:15:00 UTC,heat,hold,672,683,683,KY,Georgetown,120,False,False,True,Electric,2020,dec
465173,628b89c27b7633e93a2abe430b726e3018266a4a,2020-12-23 18:10:00 UTC,heat,hold,704,710,710,KY,Georgetown,120,False,False,True,Electric,2020,dec

In [160]:
dec_2020_ave = dec_2020.groupby(['Identifier', 'Month', 'Year','HvacMode','CalendarEvent', 'City']).mean()

# dec_2020_ave

In [161]:
# Export CSV file

dec_2020_ave.to_csv("data/day/KY/dec/dec_2020_ave.csv", header=True, index=True)

---

### Combine month CSV Files 
1. Read in files in folders for each state
2. Export as combined CSV

In [162]:
# Create variable for files in directory
files = [f for f in os.listdir("data/day/KY/dec/") if f.endswith(".csv")]

# files

In [163]:
# https://stackoverflow.com/questions/63886787/how-to-create-a-dataframe-from-multiple-csv-files
# InitiKYize and empty dataframe
KY_dec = pd.DataFrame()

# Iterate through files and contents, then concatenate the data into the dataframe
for file in files:
    df = pd.read_csv("data/day/KY/dec/" + file)
    KY_dec = pd.concat([KY_dec, df])
    
KY_dec

,Identifier,Month,Year,HvacMode,CalendarEvent,City,Temperature_ctrl,TemperatureExpectedCool,TemperatureExpectedHeat,Age_of_Home__years_,allowCompWithAux,Has_Electric,Has_a_Heat_Pump
0,00105867bef9463f0a62d5257d0e91b8c8d19dee,dec,2017,heat,auto,Southgate,646.225490,651.176471,635.980392,75.0,False,False,False
1,00105867bef9463f0a62d5257d0e91b8c8d19dee,dec,2017,heat,hold,Southgate,676.944444,672.111111,668.222222,75.0,False,False,False
2,003e168f638289edc59e7df30f5a63ff7bae7a2e,dec,2017,heat,auto,Science Hill,720.093750,722.968750,723.562500,5.0,True,False,True
3,003e168f638289edc59e7df30f5a63ff7bae7a2e,dec,2017,heat,hold,Science Hill,713.600000,706.550000,707.350000,5.0,True,False,True
4,008cfa92481086d7def321eeabb85c0d3eb846de,dec,2017,heat,auto,Campbellsville,661.038462,661.384615,661.230769,5.0,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
701,fd8aaf4038f451870fc23ab85245f4ca4a83a354,dec,2020,auto,auto,Lexington,605.981132,631.264151,610.415094,18.0,False,False,True
702,fd8aaf4038f451870fc23ab85245f4ca4a83a354,dec,2020,auto,hold,Lexington,607.358333,708.666667,586.583333,18.0,False,False,True
703,fefca5ecf57c50c2f337a1de4577dae3d020f2cd,dec,2020,heat,auto,Lexington,728.496634,757.345417,670.538581,8.0,True,False,True
704,ff1640c73f967b557d8c64dff6f8139a85e71d38,dec,2020,auto,hold,Georgetown,681.409709,732.732039,686.102913,15.0,True,False,True
705,ffbcfc7a85b89b45816e8c216f602c018c63777e,dec,2020,auto,auto,Lexington,667.000000,739.000000,680.000000,5.0,False,False,True

In [164]:
KY_dec.to_csv("Scraper_Output/State_Month_Day/KY/KY_dec.csv", header=True, index=False)

----

----

---

### Combine state CSV Files 
1. Read in files in folders for each state
2. Export as combined CSV

In [165]:
# Create variable for files in directory
files = [f for f in os.listdir("Scraper_Output/State_Month_Day/KY/") if f.endswith(".csv")]

# files

In [166]:
# https://stackoverflow.com/questions/63886787/how-to-create-a-dataframe-from-multiple-csv-files
# InitiKYize and empty dataframe
KY_all = pd.DataFrame()

# Iterate through files and contents, then concatenate the data into the dataframe
for file in files:
    df = pd.read_csv("Scraper_Output/State_Month_Day/KY/" + file)
    KY_all = pd.concat([KY_all, df])
    
KY_all

,Identifier,Month,Year,HvacMode,CalendarEvent,City,Temperature_ctrl,TemperatureExpectedCool,TemperatureExpectedHeat,Age_of_Home__years_,allowCompWithAux,Has_Electric,Has_a_Heat_Pump
0,00105867bef9463f0a62d5257d0e91b8c8d19dee,aug,2017,cool,hold,Southgate,728.285714,700.000000,700.000000,75.0,False,False,False
1,008cfa92481086d7def321eeabb85c0d3eb846de,aug,2017,cool,auto,Campbellsville,702.335294,699.223529,680.000000,5.0,True,False,True
2,008cfa92481086d7def321eeabb85c0d3eb846de,aug,2017,cool,hold,Campbellsville,706.809160,700.091603,699.908397,5.0,True,False,True
3,020ded524bca03fd8503e9676cbd617ae62f12d4,aug,2017,auto,auto,Louisville,739.105263,739.684211,600.000000,15.0,False,False,False
4,020ded524bca03fd8503e9676cbd617ae62f12d4,aug,2017,auto,hold,Louisville,719.580153,722.005089,600.000000,15.0,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2971,fd49781b1b98414ed0495e079dd5435a549a7a86,jun,2021,heat,hold,Alexandria,703.504950,688.287129,688.287129,5.0,False,False,True
2972,fd8aaf4038f451870fc23ab85245f4ca4a83a354,jun,2021,auto,hold,Lexington,662.339726,663.895890,583.106849,18.0,False,False,True
2973,fefca5ecf57c50c2f337a1de4577dae3d020f2cd,jun,2021,cool,hold,Lexington,729.707865,720.415730,719.842697,8.0,True,False,True
2974,ff1640c73f967b557d8c64dff6f8139a85e71d38,jun,2021,auto,hold,Georgetown,691.604651,686.279070,646.674419,15.0,True,False,True
2975,ffbcfc7a85b89b45816e8c216f602c018c63777e,jun,2021,cool,hold,Lexington,723.944444,720.000000,720.000000,5.0,False,False,True

In [167]:
KY_all.to_csv("Scraper_Output/State_Month_Day/KY_all_day.csv", header=True, index=False)

In [168]:
# Datacheck to make sure state was selected correctly in BD sql queries

print(f"Unique jan_2017: {jan_2017['ProvinceState'].unique()}")
print(f"Unique jan_2018: {jan_2018['ProvinceState'].unique()}")
print(f"Unique jan_2019: {jan_2019['ProvinceState'].unique()}")
print(f"Unique jan_2020: {jan_2020['ProvinceState'].unique()}")
print(f"Unique jan_2021: {jan_2021['ProvinceState'].unique()}")
print(f"Unique feb_2017: {feb_2017['ProvinceState'].unique()}")
print(f"Unique feb_2018: {feb_2018['ProvinceState'].unique()}")
print(f"Unique feb_2019: {feb_2019['ProvinceState'].unique()}")
print(f"Unique feb_2020: {feb_2020['ProvinceState'].unique()}")
print(f"Unique feb_2021: {feb_2021['ProvinceState'].unique()}")
print(f"Unique jun_2017: {jun_2017['ProvinceState'].unique()}")
print(f"Unique jun_2018: {jun_2018['ProvinceState'].unique()}")
print(f"Unique jun_2019: {jun_2019['ProvinceState'].unique()}")
print(f"Unique jun_2020: {jun_2020['ProvinceState'].unique()}")
print(f"Unique jun_2021: {jun_2021['ProvinceState'].unique()}")
print(f"Unique jul_2017: {jul_2017['ProvinceState'].unique()}")
print(f"Unique jul_2018: {jul_2018['ProvinceState'].unique()}")
print(f"Unique jul_2019: {jul_2019['ProvinceState'].unique()}")
print(f"Unique jul_2020: {jul_2020['ProvinceState'].unique()}")
print(f"Unique jul_2021: {jul_2021['ProvinceState'].unique()}")
print(f"Unique aug_2017: {aug_2017['ProvinceState'].unique()}")
print(f"Unique aug_2018: {aug_2018['ProvinceState'].unique()}")
print(f"Unique aug_2019: {aug_2019['ProvinceState'].unique()}")
print(f"Unique aug_2020: {aug_2020['ProvinceState'].unique()}")
print(f"Unique dec_2017: {dec_2017['ProvinceState'].unique()}")
print(f"Unique dec_2018: {dec_2018['ProvinceState'].unique()}")
print(f"Unique dec_2019: {dec_2019['ProvinceState'].unique()}")
print(f"Unique dec_2020: {dec_2020['ProvinceState'].unique()}")

Unique jan_2017: ['KY']
Unique jan_2018: ['KY']
Unique jan_2019: ['KY']
Unique jan_2020: ['KY']
Unique jan_2021: ['KY']
Unique feb_2017: ['KY']
Unique feb_2018: ['KY']
Unique feb_2019: ['KY']
Unique feb_2020: ['KY']
Unique feb_2021: ['KY']
Unique jun_2017: ['KY']
Unique jun_2018: ['KY']
Unique jun_2019: ['KY']
Unique jun_2020: ['KY']
Unique jun_2021: ['KY']
Unique jul_2017: ['KY']
Unique jul_2018: ['KY']
Unique jul_2019: ['KY']
Unique jul_2020: ['KY']
Unique jul_2021: ['KY']
Unique aug_2017: ['KY']
Unique aug_2018: ['KY']
Unique aug_2019: ['KY']
Unique aug_2020: ['KY']
Unique dec_2017: ['KY']
Unique dec_2018: ['KY']
Unique dec_2019: ['KY']
Unique dec_2020: ['KY']